#!/command/with-contenv bash

if [ -f $WEBHOME/composer.json ] && [ ! -e $WEBHOME/vendor/ ]; then
    /usr/bin/composer install \
        --no-ansi \
        --no-dev \
        --no-interaction \
        --no-plugins \
        --no-progress \
        --no-scripts \
        --optimize-autoloader
fi