#!/command/with-contenv bash

if [ -f $WEBHOME/composer.json ] && [ ! -e $WEBHOME/vendor/ ]; then
    dirty
    composer install -d $WEBHOME/ \
        --no-dev \
        --no-interaction \
        --no-plugins \
        --no-scripts \
        --optimize-autoloader
fi