#!/usr/bin/env sh
has-cmd composer && composer clearcache -q || true

if is-true $CLEANUP_DEV_PACKAGES; then
    EXTRA_DEPS='*-dev'
fi

APK_PACKAGES='tar xz' \
APT_PACKAGES='cpp-* xz-utils' \
exec pkg-del $EXTRA_DEPS $PHPIZE_DEPS
