#!/usr/bin/env sh
find /etc/ -name '*.dpkg-*' -or -name '*-' -exec rm -f {} \; || true
find /var/log/ -type f -exec rm -f {} \; || true
rm -rf $@ \
    /tmp/* /usr/share/doc/* /var/cache/* /var/lib/apt/lists/* /var/tmp/* \
    ~/.cache/ ~/.composer/ ~/.git/ ~/.log/ ~/.npm/ ~/.tmp/ || true
