#!/usr/bin/env sh
################################################################################
# The setups in this file belong to the project https://code.shin.company/php
# I appreciate you respecting my intellectual efforts in creating them.
# If you intend to copy or use ideas from this project, please credit properly.
# Author:  SHIN Company <shin@shin.company>
# License: https://code.shin.company/php/blob/main/LICENSE
################################################################################

run_cmd() {
    if [ -x "$1" ]; then
        debug-echo "\nAutorun: $1"
        with-env "$@"
    fi
}

for path; do
    if [ ! -z "$path" ] && [ -e "$path" ]; then
        path="$(realpath -s $path)"
        if [ -d "$path" ]; then
            find $path -type f -name '*.sh' | xargs -r chmod +x &>/dev/null
            if has-cmd run-parts; then
                with-env run-parts --new-session "$path"
            else
                for script in $(find $path -type f -perm -111 | sort -dbfi); do
                    run_cmd "$script"
                done
            fi
        else
            run_cmd "$path"
        fi
    fi
done
