#!/usr/bin/env sh
################################################################################
# The setups in this file belong to the project https://code.shin.company/php
# I appreciate you respecting my intellectual efforts in creating them.
# If you intend to copy or use ideas from this project, please credit properly.
# Author:  SHIN Company <shin@shin.company>
# License: https://code.shin.company/php/blob/main/LICENSE
################################################################################

INSTALL="0"
CERT="domain.crt"
KEY="domain.key"
DAYS=365
LENGTH=2048

while [[ $# -gt 0 ]]; do
    case $1 in
    -l | -length)
        shift
        LENGTH="$1"
        ;;
    -c | -cert-file)
        shift
        CERT="$1"
        ;;
    -k | -key-file)
        shift
        KEY="$1"
        ;;
    -d | -days)
        shift
        DAYS="$1"
        ;;
    -i | -install)
        INSTALL="1"
        ;;
    *)
        DOMAINS="${DOMAINS}${DOMAINS:+,}$1"
        ;;
    esac
    shift
done

if [ -z "$DOMAINS" ]; then
    debug-echo -i "Usage: ${0##*/} example.com www.example.com [-c domain.crt] [-k domain.key] [-d 365] [-l 4096]"
    exit 1
fi

mkdir -p "$(dirname $CERT)" "$(dirname $KEY)"
rm -rf $CERT $KEY

debug-echo -w "Generate self-signed CA for $DOMAINS."
openssl dhparam -dsaparam -out "$(dirname $CERT)"/dhparam.pem $LENGTH
openssl req -nodes -x509 -days $DAYS \
    -newkey rsa:$LENGTH -sha256 \
    -keyout $KEY -out $CERT \
    -subj "/CN=${DOMAINS}"

if [ "$INSTALL" = "1" ]; then
    if [ -f /etc/ssl/certs/ca-certificates.crt ]; then
        ln -nsf $(realpath $CERT) /etc/ssl/certs/
    elif [ -d /usr/local/share/ca-certificates ]; then
        ln -nsf $(realpath $CERT) /usr/local/share/ca-certificates/
    fi
    if has-cmd update-ca-certificates; then
        update-ca-certificates
    fi
fi
