#!/usr/bin/env sh
################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
#      - Author:  SHIN Company <shin@shin.company>
#      - License: https://code.shin.company/php/blob/main/LICENSE
################################################################################

alpine() {
    if [ $# -gt 0 ]; then
        debug-echo -e "\nRemove" $@
        apk del --no-cache --purge "$@" 2>&1 | grep -vF 'No such package' | debug-echo -l
    fi
}

debian() {
    if [ $# -gt 0 ]; then
        debug-echo -e "\nRemove" $@
        apt-get -yqq remove --purge "$@" 2>&1 | grep -vF 'so not removed' | debug-echo -l
    fi

    apt-get -yqq autoremove --purge | debug-echo -l || true
    apt-get -yqq clean | debug-echo -l || true
}

if has-cmd apk; then alpine $APK_PACKAGES "$@"; fi
if has-cmd apt; then debian $APT_PACKAGES "$@"; fi
