#!/usr/bin/env sh
################################################################################
# The setups in this file belong to the project https://code.shin.company/php
# I appreciate you respecting my intellectual efforts in creating them.
# If you intend to copy or use ideas from this project, please credit properly.
# Author:  SHIN Company <shin@shin.company>
# License: https://code.shin.company/php/blob/main/LICENSE
################################################################################

alpine() {
    if [ $# -gt 0 ]; then
        rm -rf /var/cache/apk && mkdir /var/cache/apk
        apk update | debug-echo -l
        for pkg; do
            if [ "$pkg" = "upgrade" ]; then
                apk upgrade --available | debug-echo -l
            else
                debug-echo -i "\nInstall $pkg"
                apk add $pkg | debug-echo -l
            fi
        done
    fi
}

debian() {
    local options="-yq --allow-unauthenticated"
    if [ $# -gt 0 ]; then
        apt-get update $options | debug-echo -l
        for pkg; do
            if [ "$pkg" = "upgrade" ] || [ "$pkg" = "update" ]; then
                apt-get upgrade $options | debug-echo -l
            else
                debug-echo -i "\nInstall $pkg"
                apt-get install $options --no-install-recommends --no-install-suggests $pkg | debug-echo -l
            fi
        done
    fi
}

if has-cmd apk; then alpine $APK_PACKAGES "$@"; fi
if has-cmd apt; then debian $APT_PACKAGES "$@"; fi
