#!/usr/bin/env sh
################################################################################
# The setups in this file belong to the project https://code.shin.company/php
# I appreciate you respecting my intellectual efforts in creating them.
# If you intend to copy or use ideas from this project, please credit properly.
# Author:  SHIN Company <shin@shin.company>
# License: https://code.shin.company/php/blob/main/LICENSE
################################################################################

alpine() {
    if [ $# -gt 0 ]; then
        debug-echo -e "\nRemove" $@
        apk del --no-cache --purge "$@" 2>&1 | grep -vF 'No such package' | debug-echo -l
    fi
}

debian() {
    if [ $# -gt 0 ]; then
        debug-echo -e "\nRemove" $@
        apt-get -yq remove --purge "$@" 2>&1 | grep -vF 'so not removed' | debug-echo -l
    fi

    apt-get -yq autoremove --purge | debug-echo -l || true
    apt-get -yq clean | debug-echo -l || true
}

if has-cmd apk; then alpine $APK_PACKAGES "$@"; fi
if has-cmd apt; then debian $APT_PACKAGES "$@"; fi
