#!/usr/bin/env sh
################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
#      - Author:  SHIN Company <shin@shin.company>
#      - License: https://code.shin.company/php/blob/main/LICENSE
################################################################################

keywords="update upgrade"
upgrade=0
packages=""

for arg in "$@"; do
    match=0
    for keyword in $keywords; do
        if [ "$arg" = "$keyword" ]; then
            match=1
            upgrade=1
            break
        fi
    done

    if [ "$match" -eq 0 ]; then
        packages="$packages $arg"
    fi
done

# packages="$(echo "$packages" | sed 's/^ *//')"

alpine() {
    if [ $# -gt 0 ] || [ $upgrade -eq 1 ]; then
        rm -rf /var/cache/apk && mkdir /var/cache/apk
        apk update | debug-echo -l || true
    fi
    if [ $upgrade -eq 1 ]; then
        apk upgrade --available | debug-echo -l || true
    fi
    if [ $# -gt 0 ]; then
        debug-echo -i "\nInstall $@"
        apk add "$@" | debug-echo -l
    fi
}

debian() {
    local options="-yqq --allow-unauthenticated"
    if [ $# -gt 0 ] || [ $upgrade -eq 1 ]; then
        apt-get update $options 2>&1 | grep -vF 'GPG error' | debug-echo -l || true
    fi
    if [ $upgrade -eq 1 ]; then
        apt full-upgrade $options | debug-echo -l || true
    fi
    if [ $# -gt 0 ]; then
        debug-echo -i "\nInstall $@"
        apt-get install $options --no-install-recommends --no-install-suggests "$@" | debug-echo -l
    fi
}

if has-cmd apk; then alpine $APK_PACKAGES $packages; fi
if has-cmd apt; then debian $APT_PACKAGES $packages; fi
