#!/usr/bin/env sh
################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
#      - Author:  SHIN Company <shin@shin.company>
#      - License: https://code.shin.company/php/blob/main/LICENSE
################################################################################

for dir; do
    if [ -n "$dir" ] && [ ! -f "$dir" ]; then
        mkdir -vpm 4755 "$dir"
        if [ -d "$dir" ]; then chown "$APP_USER:$APP_GROUP" "$dir"; fi
    fi
done
