#!/usr/bin/env sh
################################################################################
# The setups in this file belong to the project https://code.shin.company/php
# I appreciate you respecting my intellectual efforts in creating them.
# If you intend to copy or use ideas from this project, please credit properly.
# Author:  SHIN Company <shin@shin.company>
# License: https://code.shin.company/php/blob/main/LICENSE
################################################################################

allow_root=0
if [ "$1" == "root" ]; then
    allow_root=1
    shift
fi

command=$1
shift

if [ -z "$command" ] || [ -z "$@" ]; then
    debug-echo -w "Usage: ${0##*/} <name> <command> [options]"
    exit 1
fi

if [ "$allow_root" = "1" ]; then
    command="/usr/local/aliases/$command"
    mkdir -p "$(dirname $command)"
    echo "#!/usr/bin/env sh
if [ -d \$(app-path) ]; then cd \$(app-path); fi
exec with-env $@ \"\$@\"
" >$command
    chmod 4755 $command
else
    command="/usr/local/sbin/$command"
    mkdir -p "$(dirname $command)"
    echo "#!/usr/bin/env sh
if [ -d \$(app-path) ]; then cd \$(app-path); fi
exec web-do $@ \"\$@\"
" >$command
fi

chmod +x $command
