#!/usr/bin/env sh
################################################################################
# The setups in this file belong to the project https://code.shin.company/php
# I appreciate you respecting my intellectual efforts in creating them.
# If you intend to copy or use ideas from this project, please credit properly.
# Author:  SHIN Company <shin@shin.company>
# License: https://code.shin.company/php/blob/main/LICENSE
################################################################################

for dir; do
    if [ ! -z "$dir" ] && [ ! -f "$dir" ]; then
        mkdir -vpm 4755 "$dir"
        if [ -d "$dir" ]; then chown "$APP_USER:$APP_GROUP" "$dir"; fi
    fi
done
