#!/usr/bin/env sh
################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
#      - Author:  SHIN Company <shin@shin.company>
#      - License: https://code.shin.company/php/blob/main/LICENSE
################################################################################

for dir; do
    install -d -v \
        -g "$APP_GROUP" \
        -o "$APP_USER" \
        -m 0755 \
        -- "$dir" 2>&1 | sed 's/^install: //'
done
