#!/usr/bin/env sh
################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
#      - Author:  SHIN Company <shin@shin.company>
#      - License: https://code.shin.company/php/blob/main/LICENSE
################################################################################

allow_root=0
if [ "$1" == "root" ]; then
    allow_root=1
    shift
fi

target=$1
shift

if [ -z "$target" ] || [ $# -eq 0 ]; then
    debug-echo -i "Usage: ${0##*/} <name> <command> [options]"
    exit 1
fi

mkdir -p "/usr/local/sbin" "/usr/local/aliases"

if [ "$allow_root" = "1" ]; then
    target="/usr/local/aliases/$target"
    command="with-env"
    touch "$target" && chmod 4755 "$target"
else
    target="/usr/local/sbin/$target"
    command="web-do"
fi

echo "#!/usr/bin/env sh
set -e
if [ -d \$(app-path) ]; then cd \$(app-path); fi
exec $command $@ \"\$@\"
" >$target

chmod +x $target
