#!/usr/bin/env sh
################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
# Author:  SHIN Company <shin@shin.company>
# License: https://code.shin.company/php/blob/main/LICENSE
################################################################################

allow_root=0
if [ "$1" == "root" ]; then
    allow_root=1
    shift
fi

command=$1
shift

if [ -z "$command" ] || [ -z "$@" ]; then
    debug-echo -i "Usage: ${0##*/} <name> <command> [options]"
    exit 1
fi

if [ "$allow_root" = "1" ]; then
    command="/usr/local/aliases/$command"
    mkdir -p "$(dirname $command)"
    echo "#!/usr/bin/env sh
if [ -d \$(app-path) ]; then cd \$(app-path); fi
exec with-env $@ \"\$@\"
" >$command
    chmod 4755 $command
else
    command="/usr/local/sbin/$command"
    mkdir -p "$(dirname $command)"
    echo "#!/usr/bin/env sh
if [ -d \$(app-path) ]; then cd \$(app-path); fi
exec web-do $@ \"\$@\"
" >$command
fi

chmod +x $command
