#!/usr/bin/env sh
################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
#      - Author:  SHIN Company <shin@shin.company>
#      - License: https://code.shin.company/php/blob/main/LICENSE
################################################################################

DEFAULT_ENV=/etc/.docker-env
CACHED_ENV=/etc/default/locale

print_env() {
    # print the environment variables when no command is given
    env -0 | sort -dbfiz | tr '\0' '\n' | grep -vF '_='
}

# load extra env variables
if [ -e /etc/environment ]; then
    set -a
    source /etc/environment
    set +a
fi

# load extra env variables
if [ "$ENV" != "$DEFAULT_ENV" ] && [ -x "$DEFAULT_ENV" ]; then source "$DEFAULT_ENV"; fi
if [ -x "$ENV" ]; then source "$ENV"; fi

if [ $# -eq 0 ]; then
    # print the environment variables
    print_env
else
    # cache environment variables for other processes
    if [ "$1" = "@" ]; then
        mkdir -p "$(dirname $CACHED_ENV)" && print_env >"$CACHED_ENV"
        shift
    fi

    # execute the command
    if [ $# -gt 0 ]; then
        exec "$@"
    fi
fi
