#!/usr/bin/env sh
################################################################################
# The setups in this file belong to the project https://code.shin.company/php
# I appreciate you respecting my intellectual efforts in creating them.
# If you intend to copy or use ideas from this project, please credit properly.
# Author:  SHIN Company <shin@shin.company>
# License: https://code.shin.company/php/blob/main/LICENSE
################################################################################

config_file="${PHP_INI_DIR}-fpm.d/zz-generated-settings.conf"

# Gather system information
cpu_cores=$(grep -c ^processor /proc/cpuinfo)
ram_mb=$(free -m | awk '/^Mem:/{print $2}')

# Set PHP-FPM directives based on system specs and best practices
pm="dynamic"  # Recommended for most cases
pm_max_children=$((cpu_cores * 5))
pm_start_servers=$((cpu_cores * 2))
pm_min_spare_servers=$((cpu_cores * 1))
pm_max_spare_servers=$((cpu_cores * 3))
pm_max_requests=500

# Modify configuration file
mkdir -p "$(dirname $config_file)"
touch $config_file
sed -i '/^; Tuning PM/,$d' $config_file &>/dev/null
cat <<EOF >>$config_file
; Tuning PM
[\${PHP_POOL_NAME}]
pm = $pm
pm.max_children = $pm_max_children
pm.start_servers = $pm_start_servers
pm.min_spare_servers = $pm_min_spare_servers
pm.max_spare_servers = $pm_max_spare_servers
pm.max_requests = $pm_max_requests

EOF
