#!/usr/bin/env sh
################################################################################
# The setups in this file belong to the project https://code.shin.company/php
# I appreciate you respecting my intellectual efforts in creating them.
# If you intend to copy or use ideas from this project, please credit properly.
# Author:  SHIN Company <shin@shin.company>
# License: https://code.shin.company/php/blob/main/LICENSE
################################################################################

conf_dir="${PHP_INI_DIR}-fpm.d"
disable="$([ "${1:0:1}" = ";" ] && echo "; " || echo "")"
name="${1/;/}"; shift

if [ -d $conf_dir ]; then
    set -e
    if [ "$name" = "pool_name" ]; then
        grep -lr '^\[\(www\|\$.*\)\]' $conf_dir | xargs -r sed -i "s#^\\[\\(www\\|\\$.*\\)\\]#[$@]#g" &>/dev/null
    else
        grep -lr "^;* *${name} *=.*\$" $conf_dir | xargs -r sed -i "s#^;* *${name} *=.*\$#${disable}${name} = $@#g" &>/dev/null
    fi
fi
