#!/usr/bin/env sh
################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
#      - Author:  SHIN Company <shin@shin.company>
#      - License: https://code.shin.company/php/blob/main/LICENSE
################################################################################
if ! has-cmd php; then exit 0; fi
if [ -d "$PHP_INI_DIR" ]; then find "$PHP_INI_DIR"* -type f -name *generated-settings* -delete; fi

with-env php -d variables_order=EGPCS -- "$@" <<'DockerPHP'
<?php

define('DEBUG_MODE', (bool) trim((string) shell_exec('is-debug && echo 1 || echo 0')));

################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
################################################################################

function dd()
{
    $data = func_get_args();

    if (1 == count($data)) {
        $data = array_pop($data);
    }

    var_export($data);
    unset($data);

    exit(0);
}

function save($path, $content = '')
{
    if (is_array($content)) {
        $content = implode("\n", $content);
    }

    $date    = date('Y-m-d H:i:s');
    $content = "$content\n; Generated at $date\n\n";

    @mkdir(dirname($path), 0755, true);
    @file_put_contents($path, $content);

    if (DEBUG_MODE) {
        echo "$path\n\n$content";
    }
}

function run($command)
{
    return passthru($command);
}

################################################################################

/**
 * @class  DockerPHP
 * @author SHIN Company <shin@shin.company>
 */
final class DockerPHP
{
    const NOT_SET_VALUE = ''; // for php.ini and fpm.conf
    const NULL_VALUES   = ['no value', 'none', 'null', 'undefined', 'unknown val', 'unknown value'];
    const TRUTHY_VALUES = ['yes', 'true', 'on'];
    const FALSY_VALUES  = ['no', 'false', 'off'];
    const PHP_DEFAULTS  = [
        'daemonize'                                => 'no',
        'clear_env'                                => 'no',
        'log_buffering'                            => 'yes',
        'fastcgi.logging'                          => 'no',
        'process.dumpable'                         => 'no',
        'catch_workers_output'                     => 'yes',
        'decorate_workers_output'                  => 'no',
        'request_terminate_timeout_track_finished' => 'no',
    ];

    protected $php_env_file;
    protected $all_env_vars;
    protected $fpm_conf_path;
    protected $fpm_settings;
    protected $php_conf_path;
    protected $php_settings;

    public function __construct(
        $php_env_file  = '',
        $php_conf_file = 'custom.ini',
        $fpm_conf_file = 'custom.conf',
        $prefix = null
    ) {
        $this->php_env_file = $php_env_file;

        if (!empty($_ENV['PHP_INI_DIR'])) {
            $this->php_conf_path = "{$_ENV['PHP_INI_DIR']}/conf.d/$php_conf_file";
            $this->fpm_conf_path = "{$_ENV['PHP_INI_DIR']}-fpm.d/$fpm_conf_file";
        } else {
            $this->php_conf_path = "/etc/php/conf.d/$php_conf_file";
            $this->fpm_conf_path = "/etc/php/php-fpm.d/$fpm_conf_file";
        }

        $this->build_env_vars();
    }

    public function __set($key, $val)
    {
        $env_key = $this->env_key($key);

        if (array_key_exists($env_key, $_ENV)) {
            $val = $this->clean_val($_ENV[$env_key]);
        }

        $this->all_env_vars[$env_key] = isset($val) ? $this->env_val($val) : self::NOT_SET_VALUE;
    }

    public function __get($env_key)
    {
        if ($this->__isset($env_key)) {
            return (string) $this->all_env_vars[$env_key];
        }

        return '';
    }

    public function __isset($env_key)
    {
        return array_key_exists($env_key, $this->all_env_vars);
    }

    public function recreate_env_file($override = true) {
        if (empty($this->php_env_file)) {
            return;
        }

        @mkdir(dirname($this->php_env_file), 0755, true);

        if ($override && file_exists($this->php_env_file)) {
            @unlink($this->php_env_file);
        }

        @touch($this->php_env_file);
    }

    public function reset_envvars()
    {
        $this->export_envvars(true);
    }

    public function export_envvars($override = false)
    {
        $this->recreate_env_file();
        $command = "env-default {$this->php_env_file}";

        run("$command '# Environment variables for PHP'");

        foreach ($this->all_env_vars as $env_key => $env_val) {
            if (!$override && isset($_ENV[$env_key])) {
                continue;
            }

            run("$command '$env_key' '$env_val'");

            if (DEBUG_MODE) {
                echo "$env_key='$env_val'\n";
            }
        }

        // Cache environment variables for other processes
        run('with-env @');
    }

    public function write_static_config()
    {
        $this->write_config(false);
    }

    public function write_dynamic_config()
    {
        $this->write_config(true);
    }

    public function write_config($dynamic = false)
    {
        $defaults = self::PHP_DEFAULTS;

        $php_conf = array_merge(['[PHP]'], $this->build_conf($this->php_settings, $defaults, $dynamic), ['']);
        save($this->php_conf_path, $php_conf);
        unset($php_conf);

        $fpm_conf = [];
        foreach ($this->fpm_settings as $scope => $settings) {
            if ($scope == 'www') {
                if ($dynamic) {
                    $scope = '${PHP_POOL_NAME}';
                } else if (!empty($_ENV['PHP_POOL_NAME'])) {
                    $scope = $_ENV['PHP_POOL_NAME'];
                }
            }

            $fpm_conf[] = "[$scope]";
            $fpm_conf   = array_merge($fpm_conf, $this->build_conf($settings, $defaults, $dynamic), ['']);
        }

        save($this->fpm_conf_path, $fpm_conf);
        unset($fpm_conf);

        if (DEBUG_MODE) {
            echo implode("\n", [
                'PHP config exported:',
                '  '.$this->php_conf_path,
                '  '.$this->fpm_conf_path,
            ])."\n\n";
        }
    }

    public function list_env()
    {
        foreach ($this->all_env_vars as $env_key => $env_val) {
            echo "$env_key='$env_val'\n";
        }
    }

    public function dump()
    {
        dd([
            'php_conf_path' => $this->php_conf_path,
            'fpm_conf_path' => $this->fpm_conf_path,
            'php_settings'  => $this->php_settings,
            'fpm_settings'  => $this->fpm_settings,
            'all_env_vars'  => $this->all_env_vars,
        ]);
    }

    private function get_fpm_ini()
    {
        exec(
            "$(command -v php-fpm) -n -d log_level=notice -tt 2>&1 | sed -e 's#^.*\?NOTICE:[ \t]*##' | uniq | grep '[=\[]'",
            $lines
        );

        $outputs = [];
        $scope   = 'global';

        foreach ($lines as $line) {
            if (preg_match("/^\[(.+)\]/", $line, $matches)) {
                $scope = (strtolower($matches[1]) == 'general') ? 'global' : $matches[1];
                continue;
            }

            if (false !== strpos($line, ' = ')) {
                $parts = explode(' = ', ltrim($line), 2);
                $key   = $this->clean_key($parts[0]);

                if (empty($key)) {
                    continue;
                }

                if (!isset($outputs[$scope])) {
                    $outputs[$scope] = [];
                }

                $outputs[$scope][$key] = $this->clean_val($parts[1], $key);
            }
        }

        foreach ($outputs as &$settings) {
            ksort($settings);
        }

        return $outputs;
    }

    private function get_php_ini()
    {
        $settings = ini_get_all(null, false);
        $outputs  = [];

        foreach ($settings as $key => $val) {
            if (empty($key)) {
                continue;
            }

            $outputs[$key] = $this->clean_val($val, $key);
        }

        ksort($outputs);

        return $outputs;
    }

    private function clean_key($key)
    {
        return trim((string) $key);
    }

    private function clean_val($val, $key = null)
    {
        if (!empty($key) && array_key_exists($key, self::PHP_DEFAULTS)) {
            $val = self::PHP_DEFAULTS[$key];
        }

        if (is_string($val)) {
            $low = strtolower(trim((string) $val));
        } else {
            $low = $val;
        }

        if (is_null($val) || in_array($low, self::NULL_VALUES, true)) {
            return null;
        }

        if (in_array($low, self::TRUTHY_VALUES, true)) {
            return 'yes';
        }

        if (in_array($low, self::FALSY_VALUES, true)) {
            return 'no';
        }

        return $val;
    }

    private function env_key($key)
    {
        return 'PHP_' . trim(strtoupper(preg_replace('/[^A-Za-z0-9]+/', '_', (string) $key)), '_');
    }

    private function env_val($val)
    {
        return addcslashes((string) $val, "'");
    }

    private function build_env_vars()
    {
        $this->php_settings = $this->get_php_ini();
        $this->fpm_settings = $this->get_fpm_ini();
        $this->all_env_vars = [];

        foreach ($this->php_settings as $key => $val) {
            $this->$key = $val;
        }

        foreach ($this->fpm_settings as $scope => $settings) {
            foreach ($settings as $key => $val) {
                $this->$key = $val;
            }
        }

        ksort($this->all_env_vars);
    }

    private function build_conf($settings, $defaults = [], $dynamic = false)
    {
        $conf = [];

        // only export settings that are manually set
        $settings = array_filter($settings, function ($value, $key) use ($defaults) {
            return array_key_exists($key, $defaults) || array_key_exists($this->env_key($key), $_ENV);
        }, ARRAY_FILTER_USE_BOTH);

        // export the settings
        if (!empty($settings)) {
            foreach ($settings as $key => $val) {
                $env_key = $this->env_key($key);

                if (array_key_exists($key, $defaults)) {
                    $conf[] = "{$key} = {$defaults[$key]}";
                } elseif ($this->$env_key === '' && is_null($val)) {
                    $conf[] = ";{$key} = none";
                } elseif ($dynamic) {
                    $conf[] = "{$key} = \${{$env_key}}";
                } else {
                    if (array_key_exists($env_key, $_ENV)) {
                        $val = $this->clean_val($_ENV[$env_key]);
                    }

                    if (strstr((string) $val, '=')) {
                        $val = '"' . $val . '"';
                    }

                    $conf[] = "{$key} = {$val}";
                }
            }
        } else {
            $conf[] = '; Nothing to configure';
        }

        return $conf;
    }
}

################################################################################

date_default_timezone_set($_ENV['TZ'] ?? 'UTC');

$arguments = $argv;
array_shift($arguments);

$instance = new DockerPHP(
    '',
    'zz-generated-settings.ini',
    'zz-generated-settings.conf',
    'PHP'
);

if (empty($arguments)) {
    $arguments = ['list_env'];
}

foreach ($arguments as $action) {
    if (empty($action)) {
        continue;
    }

    $action = strtolower($action);

    if (method_exists($instance, $action)) {
        $instance->$action();
    } else {
        echo "Invalid option $action\n";
    }
}

################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
################################################################################

DockerPHP
