#!/usr/bin/env bash
################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
#      - Author:  Mai Nhut Tan <shin@shin.company>
#      - License: https://code.shin.company/php/blob/main/LICENSE
################################################################################
# exit if required commands are missing
if ! has-cmd php; then exit 1; fi

# show usage if no arguments are passed
if [ "$#" -eq 0 ]; then
    debug-echo -i "Install and enable PHP modules."
    debug-echo -i "  Usage: ${0##*/} <module> [module] [...]" >&2
    debug-echo -l "  For example: ${0##*/} gd imagick" >&2
    exit 1
fi

if ! has-cmd install-php-extensions; then
    source="https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions"
    target="/usr/local/bin/install-php-extensions"
    debug-echo -w "Binary for install-php-extensions is missing."
    debug-echo -i "Try to download it from GitHub."
    download "$source" -o "$target" && chmod +x "$target"
fi

if [ -n "$PHP_INI_DIR" ] && [ -d "$PHP_INI_DIR/conf.d" ]; then
    for module in "$@"; do
        sed -i "/^; *extension *= *$module/s/^; *//g" "$PHP_INI_DIR"/conf.d/*.ini 2>/dev/null
    done
fi

installed_mods="$(php -m 2>/dev/null | grep -v '^\[' | tr '[:upper:]' '[:lower:]')"
new_mods=""

for mod; do
    if [ -n "$mod" ] && printf '%s\n' "$installed_mods" | grep -q -w "$mod"; then
        debug-echo -l "Module $mod exists, skipping."
    else
        new_mods="${new_mods:+$new_mods }$mod"
    fi
done

[ -z "$new_mods" ] && exit 0

# install build tools if gcc is missing
if ! has-cmd gcc >/dev/null 2>&1; then
    debug-echo -i "Install build tools."
    APK_PACKAGES="tar xz" APT_PACKAGES="xz-utils" pkg-add "$PHPIZE_DEPS" curl
fi

# download PHP source if required
if [ ! -e "/usr/src/php.tar.xz" ] && [ -n "$PHP_URL" ]; then
    debug-echo -i "Download PHP source from $PHP_URL."
    download "$PHP_URL" -o /usr/src/php.tar.xz

    [ -n "$PHP_ASC_URL" ] && download "$PHP_ASC_URL" -o /usr/src/php.tar.xz.asc
fi

tmp="$(mktemp)"

set -o pipefail
debug-echo -i "Install PHP modules: $new_mods."
is-debug && env-default | grep '^IPE_' | debug-echo

export DEBIAN_FRONTEND=noninteractive DEBCONF_NOWARNINGS=yes APT_LISTCHANGES_FRONTEND=none
with-env install-php-extensions $new_mods | while IFS= read -r line || [ -n "$line" ]; do
    printf '%s\n' "$line"
    case "$line" in
        *"only for installation"*)
            printf '%s' "${line##*:}" > "$tmp"
            ;;
    esac
done | grep -vF StandW | debug-echo -m

exit_code=$?

# clean up on failure
if [ "$exit_code" -ne 0 ] && [ -f "$tmp" ]; then
    pkg-del $(cat "$tmp")
    \rm -f "$tmp"
fi

exit "$exit_code"
