#!/usr/bin/env bash
################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
#      - Author:  Mai Nhut Tan <shin@shin.company>
#      - License: https://code.shin.company/php/blob/main/LICENSE
################################################################################
if ! has-cmd php; then exit 0; fi

# show usage if no arguments are passed
if [ "$#" -eq 0 ]; then
    debug-echo -i "Disable PHP modules."
    debug-echo -i "  Usage: ${0##*/} <module> [module] [...]" >&2
    debug-echo -l "  For example: ${0##*/} gd imagick" >&2
    exit 1
fi

# ensure PHP_INI_DIR is defined and valid
if [ -n "$PHP_INI_DIR" ] && [ -d "$PHP_INI_DIR/conf.d" ]; then
    for module in "$@"; do
        debug-echo -w"Disable PHP module $module."
        # modify matching extension lines by commenting them
        sed -i "/^extension *= *$module/s/^/;/g" "$PHP_INI_DIR"/conf.d/*.ini 2>/dev/null
    done
fi
