#!/usr/bin/env sh
################################################################################
# The setups in this file belong to the project https://code.shin.company/php
# I appreciate you respecting my intellectual efforts in creating them.
# If you intend to copy or use ideas from this project, please credit properly.
# Author:  SHIN Company <shin@shin.company>
# License: https://code.shin.company/php/blob/main/LICENSE
################################################################################
if ! has-cmd php; then exit 0; fi

# show usage if no arguments are passed
if [ $# -eq 0 ]; then
    debug-echo -w "Disable PHP modules."
    debug-echo -w "  Usage: ${0##*/} <module> [module] [...]" >&2
    debug-echo -w "  For example: ${0##*/} gd imagick" >&2
    exit 1
fi

if [ -d "${PHP_INI_DIR}/conf.d" ]; then
    while [[ $# -gt 0 ]]; do
        MODULE="$1"
        PATTERN="/^extension *= *$MODULE/s/^/;/g"
        shift
        debug-echo -e "Disable PHP module $MODULE."
        sed -i "$PATTERN" "${PHP_INI_DIR}/conf.d"/*.ini &>/dev/null
    done
fi
