#!/usr/bin/env sh
################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
# Author:  SHIN Company <shin@shin.company>
# License: https://code.shin.company/php/blob/main/LICENSE
################################################################################
if ! has-cmd php; then exit 0; fi

# show usage if no arguments are passed
if [ $# -eq 0 ]; then
    debug-echo -i "Disable PHP modules."
    debug-echo -i "  Usage: ${0##*/} <module> [module] [...]" >&2
    debug-echo -l "  For example: ${0##*/} gd imagick" >&2
    exit 1
fi

if [ -d "${PHP_INI_DIR}/conf.d" ]; then
    while [[ $# -gt 0 ]]; do
        MODULE="$1"
        PATTERN="/^extension *= *$MODULE/s/^/;/g"
        shift
        debug-echo -e "Disable PHP module $MODULE."
        sed -i "$PATTERN" "${PHP_INI_DIR}/conf.d"/*.ini &>/dev/null
    done
fi
