#!/usr/bin/env sh
################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
#      - Author:  SHIN Company <shin@shin.company>
#      - License: https://code.shin.company/php/blob/main/LICENSE
################################################################################

# fix missing APP_ROOT
if [ "$APP_ROOT" != "$APP_PATH" ]; then
    web-mkdir "$APP_ROOT"
fi

################################################################################

# fix .htaccess to allow uri path after index.php
if [ -f "$APP_ROOT/.htaccess" ]; then
    debug-echo "Fix .htaccess to allow uri path after index.php."
    sed -i 's|index\.php/|index.php?/|g' "$APP_ROOT/.htaccess" &>/dev/null
fi

################################################################################

# create logs directory if it doesn't exist
if [ -n "$DEFAULT_LOG_PATH" ]; then
    web-mkdir "$(dirname "$DEFAULT_LOG_PATH")" &>/dev/null || true
fi

################################################################################

# fix ownership
if ! is-true $DISABLE_AUTORUN_FIX_OWNER_GROUP; then
    index_path="$(app-index)"
    if is-true $FIX_APP_PATH_PERMISSION || is-true $FIX_WEBHOME_PERMISSION; then
        debug-echo "Fix ownership for the application path."
        web-chown fix
    elif [ -f "$index_path" ]; then
        owner="$(ls -ld "$index_path" | awk '{print $3 ":" $4}')"
        debug-echo "Verify ownership for the application path."
        debug-echo "Detected owner: $owner"
        debug-echo "Expected owner: $APP_USER:$APP_GROUP"

        if [ "$owner" != "$APP_USER:$APP_GROUP" ]; then
            web-chown fix
        fi
    fi
    rm -rf "$(web-chown path)"
fi

