#!/command/with-contenv bash

if [[ $DEBUG_OUTPUT && $DEBUG_OUTPUT == true ]]; then
    # Set NGINX and PHP-FPM to debug mode
    sed -i 's/^\terror_log.*/\terror_log \/proc\/self\/fd\/2 debug;/' /etc/nginx/nginx.conf
    sed -i 's/^;log_level.*/log_level = debug/' /etc/php/fpm/php-fpm.conf
    echo "🔥 NGINX and PHP-FPM are in DEBUG MODE 🔥"
fi