#!/usr/bin/env sh
################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
#      - Author:  SHIN Company <shin@shin.company>
#      - License: https://code.shin.company/php/blob/main/LICENSE
################################################################################
nginx-conf 'user' "$APP_USER $APP_GROUP"
nginx-conf 'pid'  "${NGINX_PID:-/run/nginx.pid}"

# set variables
echo "
set \$APP_PATH '$APP_PATH';
set \$APP_ROOT '$APP_ROOT';
" >/etc/nginx/custom.d/00-set-variables.conf

# adjust max upload size
if [ -n "$PHP_POST_MAX_SIZE" ]; then
    echo "client_max_body_size ${PHP_POST_MAX_SIZE};" >/etc/nginx/custom.d/00-client_max_body_size.conf
fi

# adjust max timeout
if [ -n "$PHP_MAX_EXECUTION_TIME" ] && [ "$PHP_MAX_EXECUTION_TIME" -gt "0" ]; then
    echo "
send_timeout        ${PHP_MAX_EXECUTION_TIME};
client_body_timeout ${PHP_MAX_EXECUTION_TIME};
" >/etc/nginx/custom.d/00-client_body_timeout.conf

    echo "
proxy_connect_timeout ${PHP_MAX_EXECUTION_TIME};
proxy_read_timeout    ${PHP_MAX_EXECUTION_TIME};
proxy_send_timeout    ${PHP_MAX_EXECUTION_TIME};
" >/etc/nginx/custom.d/00-proxy_timeout.conf
fi

web-chown fix /var/lib/nginx /var/log/nginx /run/nginx

# turn on or off ssl_stapling
if nginx-has-error '"ssl_stapling" ignored'; then
    nginx-conf 'ssl_stapling' 'off';
else
    nginx-conf 'ssl_stapling' 'off';
fi

# enable debug logs
if is-debug; then
    nginx-conf 'error_log' "$(log-path stdout) debug"
    debug-echo -w "🐞 Nginx is in DEBUG MODE 🐞"
else
    nginx-conf 'error_log' "$(log-path stderr) error"
fi

if ! is-true "$DISABLE_GREETING" && has-cmd nginx; then
    nginx -v 2>&1
fi

exec with-env nginx -t
