#!/usr/bin/env sh
################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
#      - Author:  SHIN Company <shin@shin.company>
#      - License: https://code.shin.company/php/blob/main/LICENSE
################################################################################

while [ "$#" -gt 0 ]; do
    module="$1"
    pattern="/^LoadModule ${module}_module/s/^/#/g"
    shift

    debug-echo -e "disable apache module: $module"

    if ! sed -i "$pattern" /etc/apache2/*.conf 2>/dev/null; then
        debug-echo -e "failed to disable module: $module"
    fi
done
