#!/usr/bin/env sh
################################################################################
# The setups in this file belong to the project https://code.shin.company/php
# I appreciate you respecting my intellectual efforts in creating them.
# If you intend to copy or use ideas from this project, please credit properly.
# Author:  Mai Nhut Tan <shin@shin.company>
# License: https://code.shin.company/php/blob/main/LICENSE
################################################################################

while [[ $# -gt 0 ]]; do
    MODULE="$1"
    PATTERN="/^LoadModule ${MODULE}_module/s/^/#/g"
    shift
    debug-echo -e "Disable Apache module $MODULE"
    sed -i "$PATTERN" /etc/apache2/*.conf
done
