#!/usr/bin/env sh
################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
#      - Author:  SHIN Company <shin@shin.company>
#      - License: https://code.shin.company/php/blob/main/LICENSE
################################################################################

while [[ $# -gt 0 ]]; do
    MODULE="$1"
    PATTERN="/^#LoadModule ${MODULE}_module/s/^#//g"
    shift
    debug-echo -i "Enable Apache module $MODULE."
    sed -i "$PATTERN" /etc/apache2/*.conf &>/dev/null
done
