#!/usr/bin/env sh
################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
#      - Author:  Mai Nhut Tan <shin@shin.company>
#      - License: https://code.shin.company/php/blob/main/LICENSE
################################################################################
conf_dir="/etc/apache2"
disable="$( [ "${1:0:1}" = "#" ] && echo "# " || echo "" )"
name="${1/#/}"; shift

if [ -d "$conf_dir" ]; then
    find "$conf_dir" -type f -name "*.conf" -print0 | while IFS= read -r -d '' file; do
        if grep -qE "^\s*#*\s*${name}\s" "$file"; then
            sed -i -E "s~^\s*#*\s*${name}\s+.*\$~${disable}${name} $*~g" "$file"
        fi
    done
fi
