#!/command/with-contenv bash

PUID=${PUID:-9999}
PGID=${PGID:-9999}
WEBHOME=${WEBHOME:-"/var/www/html"}

if [ ! -z "$TZ" ] && [ -e /usr/share/zoneinfo/$TZ ]; then
    ln -sf /usr/share/zoneinfo/$TZ /etc/localtime
fi

if [[ $PUID != 9999 || $PGID != 9999 ]]; then
    groupmod -o -g "$PGID" webgroup
    usermod  -o -u "$PUID" webuser
fi

webuser-mkdir $WEBHOME