#!/command/with-contenv bash

WEBHOME="${WEBHOME:-/var/www/html}"

echo
/usr/sbin/php-fpm -v

su webuser

if [ -f $WEBHOME/composer.json ] && [ ! -e $WEBHOME/vendor/ ]; then
    echo
    echo "🤖 Installing packages from $WEBHOME/composer.json..."
    dirty
    /usr/bin/composer install -d $WEBHOME/ \
        --ansi \
        --no-dev \
        --no-interaction \
        --optimize-autoloader
fi

echo
/usr/sbin/php-fpm --nodaemonize