#!/usr/bin/env sh
################################################################################
# The setups in this file belong to the project https://code.shin.company/php
# I appreciate you respecting my intellectual efforts in creating them.
# If you intend to copy or use ideas from this project, please credit properly.
# Author:  SHIN Company <shin@shin.company>
# License: https://code.shin.company/php/blob/main/LICENSE
################################################################################

DEFAULT_USER="www-data"
DEFAULT_GROUP="www-data"
DEFAULT_UID="$(id -u $DEFAULT_USER)"
DEFAULT_GID="$(id -g $DEFAULT_USER)"

APP_PATH="$(app-path)"
APP_USER="${APP_USER:=$DEFAULT_USER}"
APP_GROUP="${APP_GROUP:=$DEFAULT_GROUP}"
APP_UID="${APP_UID:=$DEFAULT_UID}"
APP_GID="${APP_GID:=$DEFAULT_GID}"
USER_HOME="/home/${APP_USER}"

rand_id() { echo "$((RANDOM % 500 + 499))"; }

################################################################################

debug-echo "Verify group $APP_GROUP"
if [ "$APP_GROUP" != "$DEFAULT_GROUP" ]; then
    APP_GID="${APP_GID:=$(rand_id)}"
    groupadd -o -r -g $APP_GID $APP_GROUP 2>&1 >/dev/null
else
    if [ "$APP_GID" != "$DEFAULT_GID" ]; then
        groupmod -o -g $APP_GID $APP_GROUP 2>&1
        web-chown "GID changed to $APP_GROUP ($APP_GID)."
    fi
fi

debug-echo "Verify user $APP_USER"
if [ "$APP_USER" != "$DEFAULT_USER" ]; then
    APP_UID="${APP_UID:=$(rand_id)}"
    useradd -o -r -g $APP_GID \
        -G $APP_GROUP,$DEFAULT_GROUP --no-log-init \
        -d $USER_HOME -s /sbin/nologin -u $APP_UID $APP_USER 2>&1 >/dev/null
else
    usermod -g $APP_GID -G $APP_GROUP,$DEFAULT_GROUP \
        -d $USER_HOME -s /sbin/nologin $APP_USER 2>&1

    if [ "$APP_UID" != "$DEFAULT_UID" ]; then
        usermod -o -u $APP_UID $APP_USER 2>&1
        web-chown "UID changed to $APP_USER ($APP_UID)."
    fi
fi

debug-echo "Create $APP_PATH if not exists"
web-mkdir "$APP_PATH" "$USER_HOME"
