#!/usr/bin/env sh
################################################################################
# The setups in this file belong to the project https://code.shin.company/php
# I appreciate you respecting my intellectual efforts in creating them.
# If you intend to copy or use ideas from this project, please credit properly.
# Author:  SHIN Company <shin@shin.company>
# License: https://code.shin.company/php/blob/main/LICENSE
################################################################################

if has-cmd php-envvars; then
    debug-echo "Generate PHP config"
    php-envvars export_dynamic_conf 2>&1
fi

if is-true $ENABLE_TUNING_FPM && has-cmd fpm-pm; then
    debug-echo -w "Tune PHP-FPM performance"
    fpm-pm
fi
