#!/usr/bin/env sh
################################################################################
# The setups in this file belong to the project https://code.shin.company/php
# I appreciate you respecting my intellectual efforts in creating them.
# If you intend to copy or use ideas from this project, please credit properly.
# Author:  SHIN Company <shin@shin.company>
# License: https://code.shin.company/php/blob/main/LICENSE
################################################################################

APP_PATH="$(app-path)"
APP_ROOT="$(app-root)"

################################################################################

create_index() {
    local index_path="${1:-$APP_ROOT}/index.php"
    cat <<PHP >"$index_path"
<?php
// generated at $(date)
if ((bool) trim((string) shell_exec('is-debug && echo 1 || echo 0'))) {
    phpinfo();
} else {
    echo 'It works!';
}
PHP
    web-chown fix "$index_path" 2>&1 >/dev/null
}

################################################################################

web-mkdir "$APP_ROOT" && cd "$APP_ROOT"

# create index.php when it doesn't exist
if ! is-true $DISABLE_AUTORUN_GENERATING_INDEX; then
    if [ -z "$(ls -A "$APP_ROOT")" ]; then
        debug-echo "Create index.php"
        create_index "$APP_ROOT"
    else
        debug-echo "Skip creating index.php because $APP_ROOT is not empty."
    fi
fi
