#!/usr/bin/env sh

if has-cmd php-envvars; then
    debug-echo "Generate PHP config"
    php-envvars export_dynamic_conf 2>&1
fi

if is-true $ENABLE_TUNING_FPM && has-cmd fpm-pm; then
    debug-echo -w "Tune PHP-FPM performance"
    fpm-pm
fi
