#!/usr/bin/env sh

# generate PHP config
if has-cmd php-envvars; then
    php-envvars export_dynamic_conf 2>&1
fi

# tune PHP-FPM performance
if is-true $ENABLE_TUNING_FPM && has-cmd fpm-pm; then
    fpm-pm
fi
