#!/usr/bin/env sh
################################################################################
# The setups in this file belong to the project https://code.shin.company/php
# I appreciate you respecting my intellectual efforts in creating them.
# If you intend to copy or use ideas from this project, please credit properly.
# Author:  SHIN Company <shin@shin.company>
# License: https://code.shin.company/php/blob/main/LICENSE
################################################################################

if is-true $DISABLE_AUTORUN_SCRIPTS; then exit 0; fi

cd "$(app-path)"
exec autorun /etc/autorun.d/ /startup/ 2>&1
