#!/usr/bin/env sh

debug-echo "Cache environment variables"
mkdir -p /etc/default && with-env | sort >/etc/default/locale

if [ -e "$(web-chown path)" ] || is-true $FIX_APP_PATH_PERMISSION || is-true $FIX_WEBHOME_PERMISSION; then
    debug-echo "Fix ownership for the application path"
    web-chown fix
fi
