#!/command/with-contenv bash

WEBHOME="${WEBHOME:-/var/www/html}"

if [ "$FIX_WEBHOME_PERMISSION" == "true" ] || [ -e /tmp/cleanup ]; then
    echo
    echo "🗂 Fixing permission for ${WEBHOME}..."
    webuser-mkdir $WEBHOME recursive
    rm -f /tmp/cleanup
fi

if [ -f /welcome.txt ]; then
    echo
    cat /welcome.txt
fi

echo "

------------------------------
  Timezone: $(date +'%Z %z')
  User UID: $(id -u webuser)
  User GID: $(id -g webuser)
------------------------------

To get support from the project owner, please contact:
    admin@appseeds.net

"