#!/command/with-contenv bash

SYMFONY_ROOT="${WEBHOME:-/var/www/html}"
SYMFONY_CONSOLE="$SYMFONY_ROOT/bin/console"

webuser-mkdir $SYMFONY_ROOT

if [ ! -f "$SYMFONY_CONSOLE" ]; then
    rm -rf $SYMFONY_ROOT/public $SYMFONY_ROOT/index.*

    echo "🤖 Installing Symfony from scratch..."
    dirty
    composer create-project \
        symfony/skeleton $SYMFONY_ROOT/ \
        --ansi \
        --no-cache \
        --no-dev \
        --no-interaction
fi

if [ -f "$SYMFONY_CONSOLE" ]; then
    if [ "$SYMFONY_INSTALL_DEVKIT" == "true" ]; then
        echo "🤖 Installing packages that you usually need to build web applications..."
        dirty
        composer require -d $SYMFONY_ROOT/ \
            --ansi \
            --no-interaction \
            --optimize-autoloader \
            webapp
    fi

    echo
    php $SYMFONY_ROOT/bin/console about
fi
