#!/bin/sh

BASE_DIR="$(git rev-parse --show-toplevel)"
BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
BUILD_DESC=
VCS_REF="$(git rev-parse HEAD)"

prebuild () {
    local source
    local dockerfile
    source="$BASE_DIR/$1"
    dockerfile=${source}/Dockerfile
    readmefile=${source}/README.md

    if [ -f $readmefile ]; then
        echo "\n\n$(cat ${BASE_DIR}/SPONSOR.md)" >>$readmefile
        BUILD_DESC="$(sed '3q;d' $readmefile)"
    fi

    if [ -f $dockerfile ]; then
        echo "\n\n$(cat ${BASE_DIR}/src/Metafile)" >>$dockerfile
    fi

    echo "::set-output name=BUILD_DATE::${BUILD_DATE}"
    echo "::set-output name=BUILD_DESC::${BUILD_DESC}"
    echo "::set-output name=VCS_REF::${VCS_REF}"
}

mkdir -p /tmp/buildx 2>/dev/null
prebuild $1