#!/usr/bin/env sh
################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
#      - Author:  SHIN Company <shin@shin.company>
#      - License: https://code.shin.company/php/blob/main/LICENSE
################################################################################

# disable TLSv1.3 when not supported
if nginx-has-error 'invalid value "TLSv1.3"'; then
    echo 'Disable TLSv1.3 because it is not supported in this Nginx version'
    nginx-conf 'ssl_protocols' 'TLSv1.2'
fi

# fix deprecated listen http2 directive for Nginx 1.25.1
if nginx-has-error 'use the "http2" directive'; then
    sed -i 's/listen \(.\+\?\) http2/listen \1/g' /etc/nginx/sites-enabled/*.conf >/dev/null 2>&1
    echo "http2 on;" >/etc/nginx/custom.d/00-ext-http2.conf
fi

# customize extensions
if nginx-has-error 'brotli'; then \rm -f /etc/nginx/custom.d/*brotli.conf; fi
if nginx-has-error 'gzip';   then \rm -f /etc/nginx/custom.d/*gzip.conf;   fi
if nginx-has-error 'http3';  then \rm -f /etc/nginx/custom.d/*http3.conf;  fi
