#!/usr/bin/env sh
APP_PATH="$(app-path)"
APP_ROOT="$(app-root)"

debug-echo "Your web application must be in ${APP_PATH}."

touch $APP_PATH/database/database.sqlite &>/dev/null
artisan storage:link &>/dev/null

if is-true $LARAVEL_AUTO_MIGRATION; then
    MIGRATION_CMD='php artisan migrate --force -n'

    if php artisan migrate --help | grep -q -- '--isolated'; then
        MIGRATION_CMD="$MIGRATION_CMD --isolated"
    fi

    eval $MIGRATION_CMD $LARAVEL_AUTO_MIGRATION_OPTIONS || true
fi
