#!/usr/bin/env sh
APP_PATH="$(app-path)"
APP_ROOT="$(app-root)"

debug-echo "Your web application must be in {$APP_PATH}."

touch $APP_PATH/database/database.sqlite &>/dev/null
artisan storage:link &>/dev/null

if is-true $LARAVEL_AUTO_MIGRATION; then
    artisan migrate --isolated --force $LARAVEL_AUTO_MIGRATION_OPTIONS || true
fi
