#!/usr/bin/env bash
target="$DOCUMENT_ROOT"

# falls back to old $APACHE_DOCUMENT_ROOT or $NGINX_DOCUMENT_ROOT if it is set
if [ -n "$APACHE_DOCUMENT_ROOT" ]; then
    target="$APACHE_DOCUMENT_ROOT"
elif [ -n "$NGINX_DOCUMENT_ROOT" ]; then
    target="$NGINX_DOCUMENT_ROOT"
fi

# check if the document root is an existing absolute path
if [ -n "$target" ] && [[ "$target" = /* ]] && [ -d "$target" ]; then
    echo $(realpath -mqs "$target")
else
    echo $(realpath -mqs "$(app-path)/$target")
fi
