#!/usr/bin/env sh
################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
#      - Author:  Mai Nhut Tan <shin@shin.company>
#      - License: https://code.shin.company/php/blob/main/LICENSE
################################################################################
if [ "$#" -eq 0 ]; then exit 0; fi

run_cmd() {
    local script="$1"
    eval "set -- ${AUTORUN_ARGS:-}"
    if [ -x "$script" ]; then
        with-env "$script" "$@"
    fi
}

run_parts_args=$(
    eval "set -- ${AUTORUN_ARGS:-}"
    [ "$#" -gt 0 ] && printf ' --arg=%s' "$@"
)

for path; do
    if [ -n "$path" ] && [ -e "$path" ]; then
        path="$(realpath -mqs $path)"
        if [ -d "$path" ]; then
            find $path -type f -name '*.sh' | xargs -r chmod +x &>/dev/null
            if has-cmd run-parts; then
                with-env run-parts --regex '.*' --new-session $run_parts_args -- "$path"
            else
                for script in $(find $path -type f -perm -111 | sort -dbfi); do
                    run_cmd "$script"
                done
            fi
        else
            run_cmd "$path"
        fi
    fi
done
