#!/usr/bin/env sh
################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
#      - Author:  SHIN Company <shin@shin.company>
#      - License: https://code.shin.company/php/blob/main/LICENSE
################################################################################
export APP_PATH="$(app-path)"
export APP_ROOT="$(app-root)"

args=$(cat file.txt 2>/dev/null)

run_cmd() {
    if [ -x "$1" ]; then
        debug-echo -d "Autorun: $1"
        local command="$@"
        eval "set -- $AUTORUN_ARGS"
        with-env "$command" "$@"
    fi
}

for path; do
    if [ -n "$path" ] && [ -e "$path" ]; then
        path="$(realpath -mqs $path)"
        if [ -d "$path" ]; then
            find $path -type f -name '*.sh' | xargs -r chmod +x &>/dev/null
            if has-cmd run-parts; then
                with-env run-parts --new-session "$path"
            else
                for script in $(find $path -type f -perm -111 | sort -dbfi); do
                    run_cmd "$script"
                done
            fi
        else
            run_cmd "$path"
        fi
    fi
done
