#!/usr/bin/env bash
usage() { du -sh / 2>/dev/null | awk '{print $1}'; }
before="$(usage)"
hook cleanup || true
echo
echo "Cleanup completed!"
debug-echo -w "Before cleanup: $before"
debug-echo -s "After cleanup:  $(usage)"
