#!/usr/bin/env sh
welcome_txt=/etc/welcome.txt
license_txt=/license
user="${APP_USER:=www-data}"
group="${APP_GROUP:=www-data}"

arch="$(uname -m)"
case "$arch" in
    x86_64) arch=amd64 ;;
    aarch64) arch=arm64 ;;
    armv7l|armv7*) arch=arm/v7 ;;
    i?86) arch=386 ;;
esac

echo "
$([ -f "$welcome_txt" ] && cat "$welcome_txt" | sed "s#%PATH%#$welcome_txt#g")
---------------
$([ -f "$license_txt" ] && cat "$license_txt" | sed "s#%EMAIL%#${MAINTAINER:-shin@shin.company}#g" | sed "s#%YEAR%#$(date +'%Y')#g")

---------------
Container     : ${DOCKER_NAME:-shinsenter/php} (built: ${DOCKER_DATE:-$(date +'%Y-%m-%dT%T%z')})
Distro        : $(source /etc/os-release && echo ${PRETTY_NAME:-Unknown}) (arch: linux/$arch)
Timezone      : $(date +'%Z') (GMT$(date +'%z'))
UID / GID     : $user:$group ($(id -u $user):$(id -g $user))
App Root      : $APP_PATH
Document Root : $APP_ROOT
---------------
"
if [ -n "$S6_VERSION" ]; then echo "With s6-overlay $S6_VERSION"; fi
if has-cmd php-fpm;  then php-fpm -v; elif has-cmd php; then php -v; fi
if has-cmd composer; then composer -V 2>&1 | head -n1; fi
