#!/usr/bin/env sh
################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
#      - Author:  SHIN Company <shin@shin.company>
#      - License: https://code.shin.company/php/blob/main/LICENSE
################################################################################
if [ "$#" -eq 0 ]; then exit 0; fi
mkdir -p /tmp/hooks 2>/dev/null
for hook; do
    debug-echo -d "Hook: $hook"
    touch   "/tmp/hooks/$hook" || true
    autorun "/etc/hooks/$hook"
done
