#!/usr/bin/env bash
################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
#      - Author:  Mai Nhut Tan <shin@shin.company>
#      - License: https://code.shin.company/php/blob/main/LICENSE
################################################################################
if [ "$#" -eq 0 ]; then exit 0; fi
web-mkdir /tmp/hooks &>/dev/null
for hook; do
    debug-echo -d "Hook: $hook"
    touch "/tmp/hooks/$hook" || true
    in-app autorun "/etc/hooks/$hook" "$APP_PATH/hooks/$hook"
done
