#!/usr/bin/env bash
################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
#      - Author:  Mai Nhut Tan <shin@shin.company>
#      - License: https://code.shin.company/php/blob/main/LICENSE
################################################################################
if [ "$#" -eq 0 ]; then exit 1; fi

case "$(echo "$1" | tr '[:upper:]' '[:lower:]')" in
    ''|'false'|'none'|'null'|'off'|'undefined'|0|false|no)
        exit 1 ;;
    *)  exit 0 ;;
esac
