#!/usr/bin/env sh
################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
#      - Author:  Mai Nhut Tan <shin@shin.company>
#      - License: https://code.shin.company/php/blob/main/LICENSE
################################################################################
alpine() {
    if [ "$#" -gt 0 ]; then
        apk del --no-cache --purge "$@"
    fi
}

debian() {
    export DEBIAN_FRONTEND=noninteractive DEBCONF_NOWARNINGS=yes APT_LISTCHANGES_FRONTEND=none
    if [ "$#" -gt 0 ]; then
        apt-get -yqq --purge remove "$@"
    fi
    apt-get -yqq --purge autoremove || true
    apt-get -yqq clean || true
}

################################################################################
if has-cmd apk; then
    debug-echo -w "Removing" $APK_PACKAGES $@
    alpine $APK_PACKAGES "$@" 2>&1 | while IFS= read -r line || [ -n "$line" ]; do
        echo "$line" | grep -vF 'No such package' | debug-echo -l
    done
fi
if has-cmd apt; then
    debug-echo -w "Removing" $APT_PACKAGES $@
    debian $APT_PACKAGES "$@" 2>&1 | while IFS= read -r line || [ -n "$line" ]; do
        echo "$line" | grep -vF 'so not removed' | debug-echo -l
    done
fi
