#!/usr/bin/env sh
################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
#      - Author:  Mai Nhut Tan <shin@shin.company>
#      - License: https://code.shin.company/php/blob/main/LICENSE
################################################################################
keywords="update upgrade"
upgrade=0
packages=""

for arg in "$@"; do
    match=0
    for keyword in $keywords; do
        if [ "$arg" = "$keyword" ]; then
            match=1
            upgrade=1
            break
        fi
    done

    if [ "$match" -eq 0 ]; then
        packages="$packages $arg"
    fi
done

# packages="$(echo "$packages" | sed 's/^ *//')"

################################################################################

alpine() {
    if [ "$#" -gt 0 ] || [ "$upgrade" -eq 1 ]; then
        \rm -rf /var/cache/apk && mkdir /var/cache/apk
        apk update || true
    fi
    if [ "$upgrade" -eq 1 ]; then
        apk upgrade --available || true
    fi
    if [ "$#" -gt 0 ]; then
        apk add "$@"
    fi
}

debian() {
    local options="-y --allow-unauthenticated"
    export DEBIAN_FRONTEND=noninteractive DEBCONF_NOWARNINGS=yes APT_LISTCHANGES_FRONTEND=none
    if [ "$#" -gt 0 ] || [ "$upgrade" -eq 1 ]; then
        apt-get $options -qq update || true
    fi
    if [ "$upgrade" -eq 1 ]; then
        apt-get $options -qq full-upgrade || true
    fi
    if [ "$#" -gt 0 ]; then
        apt-get $options -q --no-install-recommends --no-install-suggests install "$@"
    fi
}

################################################################################

if has-cmd apk; then
    debug-echo -i "Installing" $APK_PACKAGES $packages
    alpine $APK_PACKAGES $packages 2>&1 | while IFS= read -r line || [ -n "$line" ]; do
        echo "$line" | debug-echo -l
    done
fi
if has-cmd apt; then
    debug-echo -i "Installing" $APT_PACKAGES $packages
    debian $APT_PACKAGES $packages 2>&1 | while IFS= read -r line || [ -n "$line" ]; do
        echo "$line" | grep -v ' warning:\|GPG error' | debug-echo -l
    done
fi
