#!/usr/bin/env sh
################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
#      - Author:  Mai Nhut Tan <shin@shin.company>
#      - License: https://code.shin.company/php/blob/main/LICENSE
################################################################################
set -e

target="$1"
if [ -z "$target" ]; then
    shift
elif [ "${target:0:1}" = "/" ] || [ "${target:0:4}" = "http" ]; then
    shift
else
    target=""
fi

if [ -n "$target" ]; then
    start=$(date +%s)
    timeout="${TIMEOUT:-60}"
    # detect if target is a URL or a path
    if [ "${target:0:4}" = "http" ]; then
        while true; do
            if curl -A "${DOCKER_NAME:-internal}-checker" -sk --max-time 2 -o /dev/null "$target"; then break; fi
            if [ "$timeout" -gt 0 ] && [ $(( $(date +%s) - start )) -ge "$timeout" ]; then
                debug-echo -c "Timeout waiting for $target."
                exit 1
            fi
            sleep 5
        done
    else
        while [ ! -S "$target" ]; do
            sleep 0.5
            if [ "$timeout" -gt 0 ] && [ $(( $(date +%s) - start )) -ge "$timeout" ]; then
                debug-echo -c "Timeout waiting for $target."
                exit 1
            fi
        done
    fi

    debug-echo "Target $target is ready."
fi

if [ "$#" -gt 0 ]; then
    exec app-exec with-env "$@"
fi
