#!/usr/bin/env sh
################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
#      - Author:  Mai Nhut Tan <shin@shin.company>
#      - License: https://code.shin.company/php/blob/main/LICENSE
################################################################################
set -e

if [ "$#" -gt 0 ]; then
    case "$1" in
    http*|/*) target="$1"; shift ;;
    *) target="" ;;
    esac
fi

curl_status() {
    curl -A "${DOCKER_NAME:-shinsenter/php}/health-checker" \
        -sk --max-time 2 \
        -o /dev/null \
        -w "%{http_code}" \
        -- "$1"
}

if [ -n "$target" ]; then
    timeout="${TIMEOUT:-60}"
    start=$(date +%s)

    # decide checking mode and sleep interval
    if [ "${target#http}" != "$target" ]; then
        mode="http"
        sleep_interval=5
    else
        mode="socket"
        sleep_interval=1
    fi

    while true; do
        elapsed=$(( $(date +%s) - start ))
        remaining=$(( timeout - elapsed ))
        if [ "$remaining" -le "$sleep_interval" ]; then
            debug-echo -c "Timeout waiting for $target." >&2
            exit 1
        fi
        if [ "$mode" = "http" ]; then
            # check http
            curl_status "$target" | grep -qE '^[1-4][0-9]{2}$' && break
        else
            # check socket
            [ -S "$target" ] && break
        fi
        sleep "$sleep_interval"
    done

    debug-echo "Target $target is ready." >&2
fi

[ "$#" -eq 0 ] && exit 0
exec in-app "$@"
