#!/usr/bin/env sh
################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
#      - Author:  SHIN Company <shin@shin.company>
#      - License: https://code.shin.company/php/blob/main/LICENSE
################################################################################
set -e

socket="$1"
if [ "${socket:0:1}" = "/" ]; then
    shift
else
    socket=""
fi

if [ -n "$socket" ]; then
    start=$(date +%s)
    timeout="${TIMEOUT:-60}"
    while [ ! -S "$socket" ]; do
        sleep 0.5
        if [ "$timeout" -gt 0 ] && [ $(( $(date +%s) - start )) -ge "$timeout" ]; then
            debug-echo -c "Timeout waiting for $socket."
            exit 1
        fi
    done

    debug-echo "Socket $socket is ready."
fi

if [ "$#" -gt 0 ]; then
    exec app-exec with-env "$@"
fi
