#!/usr/bin/env sh
################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
#      - Author:  Mai Nhut Tan <shin@shin.company>
#      - License: https://code.shin.company/php/blob/main/LICENSE
################################################################################
if has-cmd su-exec; then
    exec su-exec "$APP_USER:$APP_GROUP" "$@"
else
    exec chroot --userspec="$APP_USER:$APP_GROUP" / "$@"
fi
