#!/usr/bin/env bash
################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
#      - Author:  Mai Nhut Tan <shin@shin.company>
#      - License: https://code.shin.company/php/blob/main/LICENSE
################################################################################
allow_root=0
if [ "$1" == "root" ]; then
    allow_root=1
    shift
fi

name="$1"
shift

if [ -z "$name" ] || [ "$#" -eq 0 ]; then
    debug-echo -i "Usage: ${0##*/} <name> <command> [options]"
    exit 1
fi

mkdir -p "/usr/local/sbin" "/usr/local/aliases"

if [ "$allow_root" -eq 1 ]; then
    target="/usr/local/aliases/$name"
    command="$@"
    touch "$target" && chmod 4755 "$target"
else
    target="/usr/local/sbin/$name"
    command="web-do $@"
fi

echo "#!/usr/bin/env bash
exec in-app $command \"\$@\"
" >$target
chmod +x $target
