#!/usr/bin/env sh
################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
#      - Author:  SHIN Company <shin@shin.company>
#      - License: https://code.shin.company/php/blob/main/LICENSE
################################################################################
SYSTEM_ENV="/etc/environment"
DEFAULT_ENV="$(env-path @)"

print_env() {
    # print the environment variables when no command is given
    env -0 | sort -dbfiz | tr '\0' '\n' | grep -vF '_='
}

# load extra env variables
if [ -f "$SYSTEM_ENV" ]; then
    set -a
    source "$SYSTEM_ENV" &>/dev/null
    set +a
fi

# load extra env variables
if [ -f "$DEFAULT_ENV" ]; then source "$DEFAULT_ENV" &>/dev/null; fi
if [ -f "$ENV" ] && [ "$ENV" != "$DEFAULT_ENV" ]; then source "$ENV" &>/dev/null; fi

if [ "$#" -eq 0 ]; then
    # print the environment variables
    print_env | debug-echo -l
else
    # cache environment variables for other processes
    if [ "$1" = "@" ]; then
        mkdir -pm 0755 /etc/default
        print_env >/etc/default/locale
        shift
    fi

    # execute the command
    if [ "$#" -gt 0 ]; then
        export APP_PATH="$(app-path)"
        export APP_ROOT="$(app-root)"
        exec "$@"
    fi
fi
