#!/usr/bin/env sh
################################################################################
# The setups in this file belong to the project https://code.shin.company/php
# I appreciate you respecting my intellectual efforts in creating them.
# If you intend to copy or use ideas from this project, please credit properly.
# Author:  SHIN Company <shin@shin.company>
# License: https://code.shin.company/php/blob/main/LICENSE
################################################################################

APP_PATH="$(app-path)"
APP_ROOT="$(app-root)"
WPCONFIG_URL=https://raw.githubusercontent.com/docker-library/wordpress/master/wp-config-docker.php

web-mkdir "$APP_PATH" "$WP_CLI_DIR" "$WP_CLI_CACHE_DIR" "$WP_CLI_PACKAGES_DIR"

# create wordpress project
if ! is-true $DISABLE_AUTORUN_CREATING_PROJECT; then
    if [ -z "$(ls -A "$APP_PATH")" ]; then
        debug-echo -w "Install Wordpress to $APP_PATH"
        hook pre-create-project

        cd "$APP_PATH"
        wp core download \
            --locale="${WORDPRESS_LOCALE:-en_US}" \
            --force

        if [ ! -f "$APP_PATH/wp-config.php" ]; then
            php -r "copy('$WPCONFIG_URL', '$APP_PATH/wp-config.php');"
            web-chown fix "$APP_PATH/wp-config.php" &>/dev/null
        fi

        hook post-create-project
        web-chown "Wordpress core downloaded to $APP_PATH."
    else
        debug-echo "Skip creating project because $APP_PATH is not empty."
    fi
fi
