#!/usr/bin/env sh
rm -rf /usr/src/php* || true

if has-cmd composer; then
    composer clearcache -q || true
fi

if is-true $CLEANUP_PHPDBG && has-cmd phpdbg; then
    debug-echo -w 'Removing phpdbg binary.'
    rm -rf "$(command -v phpdbg)" || true
fi

if [ -d "$PHP_EXTENSION_DIR" ]; then
    chmod -x "$PHP_EXTENSION_DIR"/*.so || true

    if has-cmd strip; then
        strip --strip-all --strip-debug "$PHP_EXTENSION_DIR"/*.so || true
    fi
fi
