#!/usr/bin/env sh
debug-echo "Remove development packages."

if is-true "$CLEANUP_DEV_PACKAGES"; then
    EXTRA_DEPS='*-dev'
fi

APK_PACKAGES='.persistent-deps tar xz' \
APT_PACKAGES='cpp-* xz-utils' \
exec pkg-del $PHPIZE_DEPS $EXTRA_DEPS
