#!/usr/bin/env bash
debug-echo "Remove PHP source."
\rm -rf /usr/src/php* || true

if has-cmd composer; then
    debug-echo "Remove Composer cache."
    composer global clearcache -q || true
    composer clearcache -q || true
fi

if is-true "$CLEANUP_PHPDBG" && has-cmd phpdbg; then
    debug-echo -w 'Remove phpdbg binary.'
    \rm -rf "$(type -P phpdbg)" || true
fi

if [ -d "$PHP_EXTENSION_DIR" ]; then
    chmod -x "$PHP_EXTENSION_DIR"/*.so || true

    if has-cmd strip; then
        strip --strip-all --strip-debug "$PHP_EXTENSION_DIR"/*.so || true
    fi
fi
