blank_issues_enabled: false
contact_links:
  - name: ✨ Request a feature
    url: https://code.shin.company/php/discussions/new?category=ideas
    about: Suggest an idea for a feature.

  - name: 🤵 Get Professional Support & Customizations
    url: mailto:shin@shin.company?subject=I%20need%20professional%20support%20for%20docker-phpfpm&body=I%20am%20looking%20for%20professional%20support%20for%20the%20Docker%20image%20shinsenter%2Fphp.%0D%0A%0D%0A
    about: Skip the line and get priority support directly from the project owner.
