#!/command/with-contenv bash
WEBHOME="$(webhome)"
if [ -f $WEBHOME/composer.json ] && [ ! -d $WEBHOME/vendor/ ]; then
    echo; echo "🤖 Installing packages from $WEBHOME/composer.json"
    composer-install -d $WEBHOME/
    wmd $WEBHOME -R &
fi