#!/usr/bin/env sh
################################################################################
# The setups in this file belong to the project https://code.shin.company/php
# I appreciate you respecting my intellectual efforts in creating them.
# If you intend to copy or use ideas from this project, please credit properly.
# Author:  SHIN Company <shin@shin.company>
# License: https://code.shin.company/php/blob/main/LICENSE
################################################################################
if [ "$(id -u)" != "0" ]; then debug-echo -e "!!! Please run this container as the root user !!!" >&2; exit 1; fi

APP_PATH="$(app-path)"

debug-echo "Initialize container"
mkdir -p "$APP_PATH"

# set timezone
export TZ="${TZ:=UTC}"
if [ ! -z "$TZ" ] && [ -e /usr/share/zoneinfo/$TZ ]; then
    ln -nsf /usr/share/zoneinfo/$TZ /etc/localtime
    echo $TZ >/etc/timezone
fi

# activity logging
touch /var/log/startup.log
echo "$(date) $(whoami)@$(hostname):$(pwd)\$ $0 $SUPERVISOR_PHP_COMMAND $@" >>/var/log/startup.log

# load the $ENV in ~/.bashrc
ENV_CHECK='if [ -x "$ENV" ]; then source "$ENV"; fi'
touch ~/.bashrc
if ! grep -qF "$ENV_CHECK" ~/.bashrc; then echo "
# load environment variables for PHP
$ENV_CHECK
" >> ~/.bashrc; fi

# export all env variables for PHP
if is-true $ALLOW_RUNTIME_PHP_ENVVARS && has-cmd php && has-cmd php-envvars; then
    debug-echo "Export all env variables for PHP"
    php-envvars export_envvars 2>&1
fi

# change working directory
if [ -d "$APP_PATH" ]; then cd "$APP_PATH"; fi

if [ ! -z "$SUPERVISOR_PHP_COMMAND" ]; then
    # run bootstrap hook to initialize the container
    hook bootstrap

    # run custom command defined in $SUPERVISOR_PHP_COMMAND
    debug-echo "Start container with the command: $SUPERVISOR_PHP_COMMAND $@"
    exec with-env $SUPERVISOR_PHP_COMMAND "$@"
else
    # run bootstrap hook to initialize the container
    if ! has-s6; then hook bootstrap; fi

    # fallback for docker-php-entrypoint
    if [ -x "/init" ]; then set -- /init "$@"; fi

    # fallback empty entrypoint
    if [ $# -eq 0 ]; then set -- /bin/sh; fi

    # start container with command
    debug-echo "Start container with the command: $@"
    exec with-env "$@"
fi
