################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
#      - Author:  Mai Nhut Tan <shin@shin.company>
#      - License: https://code.shin.company/php/blob/main/LICENSE
################################################################################

name: Publish S6

################################################################################
################################################################################

on:
  workflow_call:
    inputs:
      tag_prefix:
        required: false
        type: string
        default: ""
  workflow_dispatch:

################################################################################
################################################################################

jobs:

  s6-overlay:
    uses: ./.github/workflows/template-common.yml
    secrets: inherit
    with:
      app_name: "base-s6"
      os: "alpine"

  linux-s6:
    name: ${{ matrix.os == '' && 'debian' || matrix.os }}-s6
    uses: ./.github/workflows/template-common.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        os:
          - ""
          - "ubuntu"
          - "alpine"
    with:
      app_name: "base-os"
      os: ${{ matrix.os }}
      tag_prefix: ${{ inputs.tag_prefix }}

################################################################################
################################################################################
