################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
# Author:  SHIN Company <shin@shin.company>
# License: https://code.shin.company/php/blob/main/LICENSE
################################################################################

name: Publish PHP

################################################################################
################################################################################

on:
  workflow_call:
    inputs:
      tag_prefix:
        required: false
        type: string
        default: ""
      build_all:
        required: false
        type: boolean
        default: false
  workflow_dispatch:

################################################################################
################################################################################

jobs:

  php:
    # See: https://docs.github.com/en/webhooks/webhook-events-and-payloads#workflow_run
    if: ${{ github.event.workflow_run.conclusion == '' || github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/template-php.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        app:
          - cli
          - fpm
          - zts
    with:
      app_name: ${{ matrix.app }}
      tag_prefix: ${{ inputs.tag_prefix }}
      build_all: ${{ inputs.build_all }}

################################################################################
################################################################################
