################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
# Author:  SHIN Company <shin@shin.company>
# License: https://code.shin.company/php/blob/main/LICENSE
################################################################################

name: Publish PHP Apps

################################################################################
################################################################################

on:
  workflow_call:
    inputs:
      tag_prefix:
        required: false
        type: string
        default: ""
      build_all:
        required: false
        type: boolean
        default: false
  workflow_dispatch:
  workflow_run:
    workflows: [Publish PHP Servers]
    types:
      - completed

################################################################################
################################################################################

jobs:

  php-apps:
    # See: https://docs.github.com/en/webhooks/webhook-events-and-payloads#workflow_run
    if: ${{ github.event.workflow_run.conclusion == '' || github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/template-php.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        app:
          - app-bedrock
          - app-cakephp4
          - app-cakephp5
          - app-codeigniter4
          - app-coolify
          - app-drupal
          - app-espocrm
          - app-flarum
          - app-flightphp
          - app-grav
          - app-hyperf
          - app-invoiceshelf
          - app-kirby
          - app-laminas
          - app-laravel
          - app-magento
          - app-mautic
          - app-phpmyadmin
          - app-slim
          - app-spiral
          - app-statamic
          - app-sulu
          - app-symfony
          - app-wordpress
          - app-yii
        # include:
        #   - app: app-laravel
        #     server: [apache, nginx]
    with:
      app_name: ${{ matrix.app }}
      server: ${{ matrix.server }}
      tag_prefix: ${{ inputs.tag_prefix }}
      build_all: ${{ inputs.build_all }}

################################################################################
################################################################################
