#!/command/with-contenv bash
WLC=/welcome.txt
LCS=/license.txt
EMAIL="${MAINTAINER:-shin@shin.company}"
NAME="${IMAGE_NAME:-shinsenter/s6-ubuntu}"
WEBHOME="$(webhome)"
GREETING="

$([ -f $WLC ] && cat $WLC | sed -u "s#%PATH%#$WLC#g")

----------------------------------------
  Container : $NAME
  Distro    : $(bash -c '. /etc/os-release;echo ${PRETTY_NAME:-Unknown}')
  Timezone  : $(date +'%Z') (GMT$(date +'%z'))
  UID / GID : $(id -u webuser) / $(id -g webuser)
  Web Root  : $WEBHOME
----------------------------------------

$([ -f $LCS ] && cat $LCS | sed -u "s#%EMAIL%#$EMAIL#g")

"

if [ "$FIX_WEBHOME_PERMISSION" == "true" ] || [ -e /tmp/owner-changed ]; then
    rm -f /tmp/owner-changed
    if [ ! -z "$WEBHOME" ]; then
        echo "🗂 Fixing permission for ${WEBHOME}"
        wmd /root    -R 2>/dev/null &
        wmd $WEBHOME -R 2>/dev/null &
    fi
fi

if [ -d /startup ]; then
    echo "🗂 Looking for startup scripts"
    for script in /startup/* ; do
        if [ -x $script ]; then
            echo "  📜 Started $script in the background."
            bash -c "sleep 0.5; . $script | sed -u 's@^@${script}: @g'" &
        fi
    done
    echo
fi

exec echo "$GREETING"