#!/command/with-contenv bash
CRATER_PROJECT="${CRATER_PROJECT:-bytefury/crater}"
CRATER_ROOT="$(webhome)"
CRATER_ARTISAN="$CRATER_ROOT/artisan"

if [ ! -f "$CRATER_ARTISAN" ]; then
    wait-for-server &>/dev/null
    echo; echo "🤖 Installing $CRATER_PROJECT from scratch"
    rm -rf $CRATER_ROOT/public $CRATER_ROOT/index.*

    composer-create -d $CRATER_ROOT/ $CRATER_PROJECT $CRATER_ROOT/ --no-install
    sed -i '/Barryvdh/d' $CRATER_ROOT/config/app.php

    if [ "$(php -r 'echo PHP_VERSION_ID;')" -lt "70400" ]; then
        composer-require -d $CRATER_ROOT/ spatie/laravel-medialibrary
    fi
    if [ "$(php -r 'echo PHP_VERSION_ID;')" -ge "80000" ]; then
        composer config  -d $CRATER_ROOT/ --no-plugins allow-plugins.pestphp/pest-plugin true
        composer-install -d $CRATER_ROOT/
    fi
    wmd $CRATER_ROOT -R &
fi

if [ -f "$CRATER_ARTISAN" ]; then
    wait-for-composer
    las() { echo; php $CRATER_ARTISAN --ansi "$@" 2>&1; }

    if [ ! -f "$CRATER_ROOT/.env" ] && [ ! -f "$CRATER_ROOT/.env.${APP_ENV}" ]; then
        cp -rf "$CRATER_ROOT/.env.example" "$CRATER_ROOT/.env"
        las key:generate --force
    fi

    if [ "$CRATER_AUTO_OPTIMIZE" == "true" ]; then
        las optimize:clear
        las optimize
        # las vendor:publish --all
        wmd $CRATER_ROOT/bootstrap/cache -R &
        wmd $CRATER_ROOT/storage -R &
    fi

    if [ "$CRATER_LINK_STORAGE" == "true" ]; then
        las storage:link
        wmd $CRATER_ROOT/storage/app/public -R &
        wmd $CRATER_ROOT/public -R &
    fi

    if [ "$CRATER_AUTO_MIGRATION" == "true" ]; then
        las migrate:refresh --seed --force --isolated
    fi
fi