#!/usr/bin/env sh
################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
#      - Author:  SHIN Company <shin@shin.company>
#      - License: https://code.shin.company/php/blob/main/LICENSE
################################################################################
if ! is-true "$DISABLE_AUTORUN_FIX_OWNER_GROUP"; then
    index_path="$(app-index)"
    need_fixed=0
    if is-true "$FIX_APP_PATH_PERMISSION" || is-true "$FIX_WEBHOME_PERMISSION"; then
        need_fixed=1
    elif [ -f "$index_path" ]; then
        owner="$(ls -ld "$index_path" | awk '{print $3 ":" $4}')"
        debug-echo "Verify ownership for the application path."
        debug-echo "Detected owner: $owner"
        debug-echo "Expected owner: $APP_USER:$APP_GROUP"

        if [ "$owner" != "$APP_USER:$APP_GROUP" ]; then
            need_fixed=1
        fi
    fi

    if [ "$need_fixed" -eq 1 ]; then
        start_time=$(date +%s)
        web-chown fix
        end_time=$(date +%s)
        elapsed=$(( end_time - start_time ))
        if [ "$elapsed" -gt 10 ]; then
            debug-echo -w "The ownership-fix process ensures the user '$APP_USER' can read and write files in $APP_PATH. "
            debug-echo -w "If this takes too long and delays container startup, set the environment variable 'DISABLE_AUTORUN_FIX_OWNER_GROUP=1' to disable it."
            debug-echo -w "You'll then need to manually fix ownership yourself and rebuild the Docker image."
        fi
    fi
fi

\rm -rf "$(web-chown path)"
