#!/usr/bin/env sh
################################################################################
# The setups in this file belong to the project https://code.shin.company/php
# I appreciate you respecting my intellectual efforts in creating them.
# If you intend to copy or use ideas from this project, please credit properly.
# Author:  SHIN Company <shin@shin.company>
# License: https://code.shin.company/php/blob/main/LICENSE
################################################################################

export APP_PATH="$(app-path)"
export APP_ROOT="$(app-root)"
export APACHE_PID="${APACHE_PID:-/run/apache2.pid}"

if [ ! -z "$PHP_MAX_EXECUTION_TIME" ] && [ "$PHP_MAX_EXECUTION_TIME" -gt "0" ]; then
    echo "
Timeout ${PHP_MAX_EXECUTION_TIME}
<IfModule proxy_module>
    ProxyTimeout ${PHP_MAX_EXECUTION_TIME}
</IfModule>
" >/etc/apache2/conf-enabled/timeout.conf
fi

if ! is-true $DISABLE_GREETING && has-cmd apache2; then
    apache2 -v 2>&1
fi

if is-debug; then
    apache-conf 'LogLevel' 'debug'
    debug-echo -w "🐞 Apache is in DEBUG MODE 🐞"
    apache2 -S
else
    apache-conf 'LogLevel' '${APACHE_LOG_LEVEL}'
fi

if [ -f /etc/apache2/envvars ]; then
    source /etc/apache2/envvars
fi

web-mkdir "$APACHE_LOG_DIR" "$APACHE_LOCK_DIR" "$APACHE_RUN_DIR"
web-chown fix \
    "$APACHE_LOG_DIR" "$APACHE_LOCK_DIR" "$APACHE_RUN_DIR" \
    /var/lib/apache2 /var/log/apache2 /run/apache2

if is-true $ENABLE_TUNING_MPM; then
    debug-echo -w "Tune Apache MPM."
    apache-mpm
fi

exec apache2 -t
