#!/command/with-contenv bash
WORDPRESS_ROOT="$(webhome)"
WORDPRESS_CHECK="$WORDPRESS_ROOT/wp-content"

if [ ! -d "$WORDPRESS_CHECK" ]; then
    wait-for-server &>/dev/null
    echo; echo "🤖 Installing Wordpress from scratch"
    rm -rf $WORDPRESS_ROOT/index.*

    wp core download \
        --locale="${WORDPRESS_LOCALE:-en_US}" \
        --force
    wmd $WORDPRESS_ROOT -R &
fi

if [ -f /etc/docker-wordpress.php ]; then
    php /etc/docker-wordpress.php
fi