#!/usr/bin/env sh
debug-echo "Your application path is at ${APP_PATH}."

PMA_CONFIG="$APP_PATH/config.inc.php"

web-mkdir "$APP_PATH/tmp" "$APP_PATH/tmp/save" "$APP_PATH/tmp/upload"

if [ -f /etc/phpmyadmin-config.php ] && [ ! -f "$PMA_CONFIG" ] ; then
    cp  -p /etc/phpmyadmin-config.php "$PMA_CONFIG"
    sed -i "s/random_string_with_32_chars_long/$(php -r 'echo md5(uniqid());')/g" "$PMA_CONFIG" &>/dev/null

    chmod 0644 "$PMA_CONFIG"

    if [ -f "$APP_PATH/libraries/vendor_config.php" ]; then
        sed -i "s@'configFile'.*@'configFile' => '${PMA_CONFIG}',@" \
            "$APP_PATH/libraries/vendor_config.php" &>/dev/null
    fi
fi
