#!/command/with-contenv bash
PMA_PROJECT="${PMA_PROJECT:-phpmyadmin/phpmyadmin}"
PMA_ROOT="$(webhome)"
PMA_CONFIG="$PMA_ROOT/config.inc.php"

if [ ! -f "$PMA_CONFIG" ]; then
    wait-for-server &>/dev/null
    echo; echo "🤖 Installing $PMA_PROJECT from scratch"
    rm -rf $PMA_ROOT/index.*

    composer-create -d $PMA_ROOT/ $PMA_PROJECT $PMA_ROOT/ \
        --repository-url='https://www.phpmyadmin.net/packages.json'

    cp  -rf /etc/phpmyadmin/config.inc.php $PMA_CONFIG
    sed -i "s/random_string_with_32_chars_long/$(php -r 'echo md5(uniqid());')/g" $PMA_CONFIG
    chmod 0644 $PMA_CONFIG

    if [ -f $PMA_ROOT/libraries/vendor_config.php ]; then
        sed -i "s@'configFile'.*@'configFile' => '${PMA_CONFIG}',@" \
            $PMA_ROOT/libraries/vendor_config.php
    fi

    wmd $PMA_ROOT/tmp
    wmd $PMA_ROOT/tmp/save
    wmd $PMA_ROOT/tmp/upload
    wmd $PMA_ROOT -R &
fi