#!/command/with-contenv bash

if [[ $DEBUG_MODE && $DEBUG_MODE == true ]]; then
    # Set NGINX and PHP-FPM to debug mode
    sed -i 's/^\terror_log.*/\terror_log \/proc\/self\/fd\/2 debug;/' /etc/nginx/nginx.conf
    echo "🔥 NGINX is in DEBUG MODE 🔥"
fi