#!/usr/bin/env sh
################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
#      - Author:  Mai Nhut Tan <shin@shin.company>
#      - License: https://code.shin.company/php/blob/main/LICENSE
################################################################################

web-mkdir /config/caddy /data/caddy /etc/caddy

if ! is-true "$DISABLE_GREETING" && has-cmd frankenphp; then
    frankenphp version 2>&1
fi

if is-debug; then
    echo -e 'export CADDY_GLOBAL_OPTIONS="$CADDY_GLOBAL_OPTIONS\ndebug"' >/etc/caddy/envvars || true
    debug-echo -w "🐞 FrankenPHP is in DEBUG MODE 🐞"
else
    \rm -f /etc/caddy/envvars || true
fi
