#!/usr/bin/env sh
################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
#      - Author:  SHIN Company <shin@shin.company>
#      - License: https://code.shin.company/php/blob/main/LICENSE
################################################################################

# first run hook
FIRST_RUN_FLAG="/var/local/first-run"
if [ ! -e "$FIRST_RUN_FLAG" ]; then
    date > "$FIRST_RUN_FLAG"
    hook first-run
else
    hook rebooted
fi

hook onboot
