#!/usr/bin/env sh
################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
#      - Author:  SHIN Company <shin@shin.company>
#      - License: https://code.shin.company/php/blob/main/LICENSE
################################################################################

DEFAULT_USER="www-data"
DEFAULT_GROUP="www-data"
DEFAULT_UID="$(id -u $DEFAULT_USER)"
DEFAULT_GID="$(id -g $DEFAULT_USER)"

APP_PATH="$(app-path)"
APP_USER="${APP_USER:=$DEFAULT_USER}"
APP_GROUP="${APP_GROUP:=$DEFAULT_GROUP}"
APP_UID="${APP_UID:=$DEFAULT_UID}"
APP_GID="${APP_GID:=$DEFAULT_GID}"
USER_HOME="/home/${APP_USER}"

rand_id() { echo "$((RANDOM % 500 + 499))"; }

################################################################################

# call the pre-boot hook
hook pre-boot

################################################################################

# create user and group
debug-echo "Verify group $APP_GROUP"
if [ "$APP_GROUP" != "$DEFAULT_GROUP" ]; then
    APP_GID="${APP_GID:=$(rand_id)}"
    groupadd -o -r -g $APP_GID $APP_GROUP &>/dev/null
else
    if [ "$APP_GID" != "$DEFAULT_GID" ]; then
        groupmod -o -g $APP_GID $APP_GROUP 2>&1
        web-chown "GID changed to $APP_GROUP ($APP_GID)."
    fi
fi

debug-echo "Verify user $APP_USER"
if [ "$APP_USER" != "$DEFAULT_USER" ]; then
    APP_UID="${APP_UID:=$(rand_id)}"
    useradd -o -r -g $APP_GID \
        -G $APP_GROUP,$DEFAULT_GROUP,mail --no-log-init \
        -d $USER_HOME -s /sbin/nologin -u $APP_UID $APP_USER &>/dev/null
else
    usermod -g $APP_GID -G $APP_GROUP,$DEFAULT_GROUP,mail \
        -d $USER_HOME -s /sbin/nologin $APP_USER 2>&1

    if [ "$APP_UID" != "$DEFAULT_UID" ]; then
        usermod -o -u $APP_UID $APP_USER 2>&1
        web-chown "UID changed to $APP_USER ($APP_UID)."
    fi
fi

################################################################################

# create application directories
debug-echo "Create $APP_PATH if not exists."
web-mkdir  "$APP_PATH" "$(dirname $(log-path))" &>/dev/null
chmod 4755 "$APP_PATH"

################################################################################

# log the timestamp of the first run, then call the hook
# this is convenient for running migration scripts etc.
FIRST_RUN=/var/local/first-run
if [ ! -e "$FIRST_RUN" ]; then
    echo "$(date)" >"$FIRST_RUN"
    hook first-run
else
    hook rebooted
fi

# call the onboot hook
hook onboot
