#!/usr/bin/env sh
################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
#      - Author:  Mai Nhut Tan <shin@shin.company>
#      - License: https://code.shin.company/php/blob/main/LICENSE
################################################################################
if ! has-cmd php; then exit 0; fi

################################################################################
sample_index() {
    cat <<PHP
<?php
// generated at $(date)
if ((bool) trim((string) shell_exec('is-debug && echo 1 || echo 0'))) {
    phpinfo();
} else {
    echo 'It works!';
}
PHP
}

# create index.php when it doesn't exist
if ! is-true "$DISABLE_AUTORUN_GENERATING_INDEX"; then
    web-mkdir "$APP_ROOT"
    if [ -z "$(ls -A "$APP_ROOT")" ]; then
        index_path="$APP_ROOT/index.php"
        if [ -n "$index_path" ]; then
            debug-echo -i "Create missing $index_path."
            sample_index >"$index_path" && web-chown fix "$index_path" &>/dev/null || true
        else
            debug-echo -e "Cannot create missing $index_path."
        fi
    else
        debug-echo "Skip creating index.php because $APP_ROOT is not empty."
    fi
fi
