#!/usr/bin/env sh
################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
#      - Author:  SHIN Company <shin@shin.company>
#      - License: https://code.shin.company/php/blob/main/LICENSE
################################################################################
if ! has-cmd php; then exit 0; fi

APP_PATH="$(app-path)"
APP_ROOT="$(app-root)"

################################################################################

create_index() {
    local index_path="${1:-$APP_ROOT}/index.php"
    cat <<PHP >"$index_path"
<?php
// generated at $(date)
if ((bool) trim((string) shell_exec('is-debug && echo 1 || echo 0'))) {
    phpinfo();
} else {
    echo 'It works!';
}
PHP
    web-chown fix "$index_path" &>/dev/null
}

################################################################################

web-mkdir "$APP_ROOT" && cd "$APP_ROOT"

# create index.php when it doesn't exist
if ! is-true $DISABLE_AUTORUN_GENERATING_INDEX; then
    if [ -z "$(ls -A "$APP_ROOT")" ]; then
        debug-echo "Create index.php"
        create_index "$APP_ROOT"
    else
        debug-echo "Skip creating index.php because $APP_ROOT is not empty."
    fi
fi
