#!/usr/bin/env sh
################################################################################
# The setups in this file belong to the project https://code.shin.company/php
# I appreciate you respecting my intellectual efforts in creating them.
# If you intend to copy or use ideas from this project, please credit properly.
# Author:  SHIN Company <shin@shin.company>
# License: https://code.shin.company/php/blob/main/LICENSE
################################################################################
if ! has-cmd crond; then exit 0; fi

APP_USER="${APP_USER:-root}"
CRONTAB="/var/spool/cron/crontabs/$APP_USER"
CRONTAB_DIR="${CRONTAB_DIR:-/etc/crontab.d}"

if ! is-true $ENABLE_CRONTAB; then
    rm -f $CRONTAB
    exit 0
fi

set -e

mkdir -p "$(dirname $CRONTAB)" $CRONTAB_DIR

if is-debug; then
    echo '*  *  *  *  *  echo "DEBUG: Crontab is running as $(whoami)." | tee /tmp/cron-debug.txt' >$CRONTAB_DIR/debug
fi

cat <<CRONTAB >$CRONTAB
CRON_TZ=${CRONTAB_TZ:-${TZ:-UTC}}
HOME=${CRONTAB_HOME:-$(app-path)}
PATH=${CRONTAB_PATH:-$PATH}
$(if [ ! -z "$CRONTAB_SHELL" ];  then echo "SHELL=${CRONTAB_SHELL}"; fi)
$(if [ ! -z "$CRONTAB_MAILTO" ]; then echo "MAILTO=${CRONTAB_MAILTO}"; fi)

# Job definition:
# .---------------- minute (0 - 59)
# |  .------------- hour (0 - 23)
# |  |  .---------- day of month (1 - 31)
# |  |  |  .------- month (1 - 12) OR jan,feb,mar,apr ...
# |  |  |  |  .---- day of week (0 - 6) (Sunday=0 or 7) OR sun,mon,tue,wed,thu,fri,sat
# |  |  |  |  |
# *  *  *  *  *  command to be executed
${CRONTAB_SETTINGS}

$(if [ -d "$CRONTAB_DIR" ]; then
    for script in $(find "$CRONTAB_DIR" -type f | sort -dbfi); do
        echo -e "\n# $script"; cat "$script"
    done
fi)

CRONTAB

chmod 0600 $CRONTAB
debug-echo -i "\nCron is running as $APP_USER.\n\n### Config:\n$(crontab -u $APP_USER -l 2>/dev/null)\n"

if ! has-s6 && has-cmd crond; then
    export APP_PATH="$(app-path)"
    export APP_ROOT="$(app-root)"
    CROND_PID=/var/run/crond.pid
    if [ -f $CROND_PID ]; then kill -TERM $(cat $CROND_PID) &>/dev/null || rm -f $CROND_PID; fi
    cd $APP_PATH && with-env crond $CRONTAB_OPTIONS;
fi
