#!/usr/bin/env sh
################################################################################
# The setups in this file belong to the project https://code.shin.company/php
# I appreciate you respecting my intellectual efforts in creating them.
# If you intend to copy or use ideas from this project, please credit properly.
# Author:  SHIN Company <shin@shin.company>
# License: https://code.shin.company/php/blob/main/LICENSE
################################################################################

APP_PATH="$(app-path)"
APP_ROOT="$(app-root)"

################################################################################

# cache environment variables for other processes
mkdir -p /etc/default && with-env >/etc/default/locale

# log the timestamp of the first run, then call the hook
# this is convenient for running migration scripts etc.
if [ ! -e /etc/.first-run ]; then
    echo "$(date)" >/etc/.first-run
    hook onfirstrun
fi

################################################################################

# fix .htaccess to allow uri path after index.php
if [ -f "$APP_ROOT/.htaccess" ]; then
    debug-echo "Fix .htaccess to allow uri path after index.php"
    sed -i 's|index\.php/|index.php?/|g' "$APP_ROOT/.htaccess" &>/dev/null
fi

# fix ownership
if ! is-true $DISABLE_AUTORUN_FIX_OWNER_GROUP; then
    debug-echo "Fix ownership for the application path"
    if is-true $FIX_APP_PATH_PERMISSION || is-true $FIX_WEBHOME_PERMISSION; then
        web-chown fix
    elif [ -f "$APP_ROOT/index.php" ] && [ "$(ls -ld "$APP_ROOT/index.php" | awk '{print $3 ":" $4}')" != "$APP_USER:$APP_GROUP" ]; then
        web-chown fix
    fi
    rm -rf "$(web-chown path)"
fi
