#!/usr/bin/env sh
################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
# Author:  SHIN Company <shin@shin.company>
# License: https://code.shin.company/php/blob/main/LICENSE
################################################################################

APP_PATH="$(app-path)"
APP_ROOT="$(app-root)"

################################################################################

# fix .htaccess to allow uri path after index.php
if [ -f "$APP_ROOT/.htaccess" ]; then
    debug-echo "Fix .htaccess to allow uri path after index.php."
    sed -i 's|index\.php/|index.php?/|g' "$APP_ROOT/.htaccess" &>/dev/null
fi

################################################################################

# fix ownership
if ! is-true $DISABLE_AUTORUN_FIX_OWNER_GROUP; then
    if is-true $FIX_APP_PATH_PERMISSION || is-true $FIX_WEBHOME_PERMISSION; then
        debug-echo "Fix ownership for the application path."
        web-chown fix
    elif [ -f "$APP_ROOT/index.php" ]; then
        owner="$(ls -ld "$APP_ROOT/index.php" | awk '{print $3 ":" $4}')"
        debug-echo "Detected owner: $owner"
        debug-echo "Expected owner: $APP_USER:$APP_GROUP"

        if [ "$owner" != "$APP_USER:$APP_GROUP" ]; then
            debug-echo "Correct ownership for the application path."
            web-chown fix
        fi
    fi
    rm -rf "$(web-chown path)"
fi

################################################################################

# cache environment variables for other processes
mkdir -p /etc/default && with-env >/etc/default/locale

################################################################################

# log the timestamp of the first run, then call the hook
# this is convenient for running migration scripts etc.
FIRST_RUN=/var/local/first-run
if [ ! -e "$FIRST_RUN" ]; then
    echo "$(date)" >"$FIRST_RUN"
    hook first-run
else
    hook post-restart
fi
