#!/usr/bin/env sh

if [ -f "$APP_PATH/.env" ]; then
    if grep -qx -- 'APP_KEY=' "$APP_PATH/.env"; then
        artisan key:generate || true
    fi

    if grep -qF -- 'DB_CONNECTION=sqlite' "$APP_PATH/.env"; then
        web-do touch "$APP_PATH/database/database.sqlite" &>/dev/null
    fi
fi

if is-true "$LARAVEL_AUTO_MIGRATION"; then
    MIGRATION_CMD='artisan migrate --force -n'

    if artisan migrate --help | grep -qF -- '--isolated'; then
        MIGRATION_CMD="$MIGRATION_CMD --isolated"
    fi

    $MIGRATION_CMD $LARAVEL_AUTO_MIGRATION_OPTIONS || true
fi

artisan storage:link || true

# service settings
s6-service queue_worker $(is-true "$LARAVEL_ENABLE_QUEUE_WORKER" && echo enable || echo disable)
s6-service scheduler    $(is-true "$LARAVEL_ENABLE_SCHEDULER"    && echo enable || echo disable)
s6-service horizon      $(is-true "$LARAVEL_ENABLE_HORIZON"      && echo enable || echo disable)
s6-service pulse        $(is-true "$LARAVEL_ENABLE_PULSE"        && echo enable || echo disable)
s6-service reverb       $(is-true "$LARAVEL_ENABLE_REVERB"       && echo enable || echo disable)
