#!/usr/bin/env sh
################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
#      - Author:  Mai Nhut Tan <shin@shin.company>
#      - License: https://code.shin.company/php/blob/main/LICENSE
################################################################################

set -e

# user and group for RoadRunner
roadrunner-conf 'server.user'  "$APP_USER"
roadrunner-conf 'server.group' "$APP_GROUP"

# enable debug logs
if is-debug; then
    roadrunner-conf 'logs.level' 'debug'
    roadrunner-conf 'http.pool.debug' 'true'
    debug-echo -w "🐞 RoadRunner is in DEBUG MODE 🐞"
else
    roadrunner-conf 'logs.level' 'error'
    roadrunner-conf 'http.pool.debug' 'false'
fi

if ! is-true "$DISABLE_GREETING"; then
    /usr/local/bin/rr -v 2>&1 | head -n1
fi
