#!/usr/bin/env sh
source=https://raw.githubusercontent.com/docker-library/wordpress/master/wp-config-docker.php

debug-echo -w "Install Wordpress to $APP_PATH."

cd "$APP_PATH"
wp core download \
    --locale="${WORDPRESS_LOCALE:-en_US}" \
    --force

if [ -f "$APP_PATH/wp-config-sample.php" ]; then
    php -r "copy('$APP_PATH/wp-config-sample.php', '$APP_PATH/wp-config-sample.original.php');"
fi

php -r "copy('$source', '$APP_PATH/wp-config-sample.php');"

# wp core install \
#     --url=${WORDPRESS_URL:-localhost} \
#     --title=${WORDPRESS_TITLE:-New Website} \
#     --admin_user=${WORDPRESS_ADMIN_USER:-admin} \
#     --admin_password=${WORDPRESS_ADMIN_PASSWORD:-admin} \
#     --admin_email=${WORDPRESS_ADMIN_EMAIL:-admin@localhost} \
#     --skip-email --quiet

web-chown fix

debug-echo -s "Wordpress $(wp core version) is downloaded to $APP_PATH."
