#!/usr/bin/env sh
################################################################################
#     These setups are part of the project: https://code.shin.company/php
#     Please respect the intellectual effort that went into creating them.
#     If you use or copy these ideas, proper credit would be appreciated.
# Author:  SHIN Company <shin@shin.company>
# License: https://code.shin.company/php/blob/main/LICENSE
################################################################################

if has-cmd crond; then
    export APP_PATH="$(app-path)"
    export APP_ROOT="$(app-root)"
    CROND_PID=/var/run/crond.pid
    if [ -f $CROND_PID ]; then kill -TERM $(cat $CROND_PID) &>/dev/null || rm -f $CROND_PID; fi
    cd "$APP_PATH" && with-env crond $CRONTAB_OPTIONS;
fi
