#!/usr/bin/env sh
################################################################################
# The setups in this file belong to the project https://code.shin.company/php
# I appreciate you respecting my intellectual efforts in creating them.
# If you intend to copy or use ideas from this project, please credit properly.
# Author:  SHIN Company <shin@shin.company>
# License: https://code.shin.company/php/blob/main/LICENSE
################################################################################

if has-cmd crond; then
    export APP_PATH="$(app-path)"
    export APP_ROOT="$(app-root)"
    CROND_PID=/var/run/crond.pid
    if [ -f $CROND_PID ]; then kill -TERM $(cat $CROND_PID) &>/dev/null || rm -f $CROND_PID; fi
    cd "$APP_PATH" && with-env crond $CRONTAB_OPTIONS;
fi
