#!/command/with-contenv bash

PMA_ROOT="${WEBHOME:-/var/www/html}"
PMA_CONFIG="$PMA_ROOT/user-config"

if [ ! -d "$PMA_ROOT/user-config" ]; then
    rm -f $PMA_ROOT/index.*

    echo "🤖 Installing PHPMyAdmin from scratch..."
    dirty
    composer create-project \
        phpmyadmin/phpmyadmin $PMA_ROOT \
        --ansi \
        --no-cache \
        --no-dev \
        --no-interaction \
        --no-plugins \
        --no-scripts \
        --no-install \
        --repository-url='https://www.phpmyadmin.net/packages.json'

    rm -rf \
        $PMA_ROOT/babel.config.json \
        $PMA_ROOT/CONTRIBUTING.md \
        $PMA_ROOT/doc/html/_sources/ \
        $PMA_ROOT/examples/ \
        $PMA_ROOT/js/src/ \
        $PMA_ROOT/README.md \
        $PMA_ROOT/RELEASE-DATE-* \
        $PMA_ROOT/setup/ \
        $PMA_ROOT/templates/test/ \
        $PMA_ROOT/composer.lock \
        $PMA_ROOT/vendor

    webuser-mkdir $PMA_ROOT/tmp/upload
    webuser-mkdir $PMA_ROOT/tmp/save
    webuser-mkdir $PMA_CONFIG

    if [ ! -f "$PMA_CONFIG/config.inc.php" ]; then
        cp -p /etc/phpmyadmin/config.inc.php $PMA_CONFIG/config.inc.php
        chmod 0600 $PMA_CONFIG/*
    fi

    sed -i "s@define('CONFIG_DIR'.*@define('CONFIG_DIR', '${PMA_CONFIG}/');@" \
        $PMA_ROOT/libraries/vendor_config.php
fi