#!/usr/bin/env sh
artisan storage:link || true

if [ -f "$APP_PATH/.env" ] && grep -qF -- 'DB_CONNECTION=sqlite' "$APP_PATH/.env"; then
    web-do touch "$APP_PATH/database/database.sqlite" &>/dev/null
fi

if is-true "$LARAVEL_AUTO_MIGRATION"; then
    MIGRATION_CMD='artisan migrate --force -n'

    if artisan migrate --help | grep -qF -- '--isolated'; then
        MIGRATION_CMD="$MIGRATION_CMD --isolated"
    fi

    $MIGRATION_CMD $LARAVEL_AUTO_MIGRATION_OPTIONS || true
fi
