#!/command/with-contenv bash
SLIM_PROJECT="${SLIM_PROJECT:-slim/slim-skeleton}"
SLIM_ROOT="$(webhome)"
SLIM_CHECK="$SLIM_ROOT/src/Application"

if [ ! -d "$SLIM_CHECK" ]; then
    echo; echo "🤖 Installing $SLIM_PROJECT from scratch"
    rm -rf $SLIM_ROOT/public $SLIM_ROOT/index.*
    composer-create -d $SLIM_ROOT/ $SLIM_PROJECT $SLIM_ROOT/
    wmd $SLIM_ROOT -R &
fi