#!/command/with-contenv bash

LARAVEL_ROOT="${WEBHOME:-/var/www/html}"
LARAVEL_ARTISAN="$LARAVEL_ROOT/artisan"

webuser-mkdir $LARAVEL_ROOT

if [ ! -f "$LARAVEL_ARTISAN" ]; then
    rm -rf $LARAVEL_ROOT/public $LARAVEL_ROOT/index.*

    echo "🤖 Installing Laravel from scratch..."
    dirty
    composer create-project \
        laravel/laravel $LARAVEL_ROOT/ \
        --ansi \
        --no-cache \
        --no-dev \
        --no-interaction
fi

silent_artisan () {
    php $LARAVEL_ARTISAN --ansi $@ 2>/dev/null
}

if [ -f "$LARAVEL_ARTISAN" ]; then
    if [ "$LARAVEL_AUTO_OPTIMIZE" == "true" ]; then
        dirty
        silent_artisan optimize:clear
        silent_artisan optimize
    fi

    if [ "$LARAVEL_LINK_STORAGE" == "true" ]; then
        dirty
        silent_artisan storage:link
    fi

    if [ "$LARAVEL_AUTO_MIGRATION" == "true" ]; then
        dirty
        silent_artisan migrate:refresh --seed --force
    fi
fi
