#!/command/with-contenv bash
YII_PROJECT="${YII_PROJECT:-yiisoft/yii2-app-basic}"
YII_ROOT="$(webhome)"
YII_CHECK="$YII_ROOT/yii"

if [ ! -f "$YII_CHECK" ]; then
    wait-for-server &>/dev/null
    echo; echo "🤖 Installing $YII_PROJECT from scratch"
    rm -rf $YII_ROOT/web $YII_ROOT/index.*

    if [ "$(php -r 'echo PHP_VERSION_ID;')" -lt "70400" ]; then
        composer-create  -d $YII_ROOT/ $YII_PROJECT $YII_ROOT/ --no-install
        composer config  -d $YII_ROOT/ --no-plugins allow-plugins.yiisoft/yii2-composer true
        composer-install -d $YII_ROOT/
    else
        composer-create  -d $YII_ROOT/ $YII_PROJECT $YII_ROOT/
    fi

    wmd $YII_ROOT -R &
fi