#!/command/with-contenv bash
if [ "$ENABLE_CRONTAB" == "true" ]; then
    WEBUSER="${WEBUSER:-www-data}"
    if [ -d /etc/cron.d ]; then
        chown -R root:root /etc/cron.d
        find /etc/cron.d -type f | xargs -I {} sed -i "s/webuser/${WEBUSER}/g" {}
        find /etc/cron.d -type f | xargs -I {} chmod 0644 {}
        bash -c 'sleep 5; find /etc/cron.d -type f | xargs -I {} touch {} 2>/dev/null' &
    fi
    echo "⚙️ Starting crontab..."
    MAILTO="" exec cron -flnL15
else
    exec s6-svc -Od .
fi