#!/command/with-contenv bash

CI4_ROOT="${WEBHOME:-/var/www/html}"
CI4_CHECK="$CI4_ROOT/vendor/codeigniter4"

webuser-mkdir "$CI4_ROOT"

if [ ! -d "$CI4_CHECK" ]; then
    rm -rf $CI4_ROOT/public $CI4_ROOT/index.*

    echo "🤖 Installing CodeIgniter 4 from scratch..."
    dirty
    composer create-project \
        codeigniter4/appstarter $CI4_ROOT/ \
        --ansi \
        --no-cache \
        --no-dev \
        --no-interaction
fi