#!/command/with-contenv bash
FUEL_PROJECT="${FUEL_PROJECT:-fuel/fuel}"
FUEL_ROOT="$(webhome)"
FUEL_CHECK="$FUEL_ROOT/fuel/app"

if [ ! -d "$FUEL_CHECK" ]; then
    wait-for-fpm &>/dev/null
    echo; echo "🤖 Installing $FUEL_PROJECT from scratch"
    rm -rf $FUEL_ROOT/public $FUEL_ROOT/index.*

    # if [ "$(php -r 'echo PHP_VERSION_ID;')" -lt "50400" ]; then
        composer-create  -d $FUEL_ROOT/ $FUEL_PROJECT $FUEL_ROOT/ --no-install
        composer config  -d $FUEL_ROOT/ --no-plugins allow-plugins.composer/installers true
        composer-install -d $FUEL_ROOT/
    # else
    #     composer-create  -d $FUEL_ROOT/ $FUEL_PROJECT $FUEL_ROOT/
    # fi

    wmd $FUEL_ROOT -R &
fi