################################################################################
# The setups in this file belong to the project https://code.shin.company/php
# I appreciate you respecting my intellectual efforts in creating them.
# If you intend to copy or use ideas from this project, please credit properly.
# Author:  SHIN Company <shin@shin.company>
# License: https://code.shin.company/php/blob/main/LICENSE
################################################################################

name: Publish PHP Servers

################################################################################
################################################################################

on:
  workflow_call:
    inputs:
      tag_prefix:
        required: false
        type: string
        default: ""
  workflow_dispatch:
  workflow_run:
    workflows: [Publish PHP]
    types:
      - completed

################################################################################
################################################################################

jobs:

  php-servers:
    # See: https://docs.github.com/en/webhooks/webhook-events-and-payloads#workflow_run
    if: ${{ github.event.workflow_run.conclusion == '' || github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/template-php.yml
    secrets: inherit
    strategy:
      max-parallel: 11
      matrix:
        app:
          - with-apache
          - with-nginx
          - with-roadrunner
          - with-f8p
          - with-unit
    with:
      app_name: ${{ matrix.app }}
      tag_prefix: ${{ inputs.tag_prefix }}

################################################################################
################################################################################
