name: DevSkim
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 2'
jobs:
  lint:
    name: DevSkim
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - uses: microsoft/DevSkim-Action@v1
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: devskim-results.sarif
